Repository GAMZA-BAT/algohub-client, pull requests merged in 2024-11, with the labels that each got.

#182 [ Feat ] 동적 라우팅 설정
  src/app/[user]/create-group/page.tsx
  src/app/[user]/join-group/page.tsx
  src/app/[user]/layout.tsx
  src/app/[user]/page.tsx
  src/app/[user]/setting/layout.tsx
  src/app/[user]/setting/page.tsx
  src/app/group/[groupId]/layout.tsx
  src/app/group/[groupId]/my-solved/page.tsx
  src/app/group/[groupId]/notice/page.tsx
  src/app/group/[groupId]/page.css.ts
  src/app/group/[groupId]/page.tsx
  src/app/group/[groupId]/problem-list/[id]/page.tsx
  src/app/group/[groupId]/problem-list/page.tsx
  src/app/group/[groupId]/setting/page.tsx
  src/app/group/[groupId]/solved-detail/[id]/page.tsx
  src/app/group/[groupId]/withdraw/page.tsx
  src/shared/component/ProblemList/Item.tsx
  src/shared/hook/useGetGroupId.ts
  src/view/group/dashboard/NoticeBanner/index.tsx
  src/view/group/my-solved/SolvedItem/index.tsx
  src/view/group/problem-list/PendingList/Item.tsx
  src/view/user/index/GroupCard/index.tsx
Labels: ✨ Feat, JIN, size/m

#183 [ Feat ] Solution, Comment API 연동 및 SSR + RQ 세팅
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/api/comment/index.ts
  src/api/index.ts
  src/api/solution/index.ts
  src/api/solution/type.ts
  src/app/group/[groupId]/page.tsx
  src/app/group/[groupId]/problem-list/[id]/page.tsx
  src/app/group/[groupId]/solved-detail/[id]/action.ts
  src/app/group/[groupId]/solved-detail/[id]/page.tsx
  src/app/group/[groupId]/solved-detail/[id]/query.ts
  src/app/layout.tsx
  src/app/provider.tsx
  src/common/component/Textarea/index.css.ts
  src/common/hook/useToast.ts
  src/shared/component/CommentBox/CommentBox.stories.tsx
  src/shared/component/CommentBox/index.css.ts
  src/shared/component/CommentBox/index.tsx
  src/shared/component/CommentInput/index.tsx
  src/shared/constant/api.ts
  src/shared/hook/useGetGroupId.ts
  src/view/group/my-solved/SolvedItem/index.css.ts
  src/view/group/my-solved/SolvedItem/index.tsx
  src/view/group/problem-list/SolvedList/SolvedTable.tsx
  src/view/group/problem-list/SolvedList/index.css.ts
  src/view/group/problem-list/SolvedList/index.tsx
  src/view/group/solved-detail/CodeSection/index.tsx
  src/view/group/solved-detail/CommentSection/index.tsx
  src/view/group/solved-detail/CommentSection/provider.tsx
Labels: ✨ Feat, WUZ, size/l

#186 [ Feat ] Feature detection을 통한 미지원 브라우저 감지
  src/app/browserProvider.tsx
  src/app/layout.tsx
  src/asset/svg/icn_chrome.svg
  src/asset/svg/icn_edge.svg
  src/asset/svg/icn_firefox.svg
  src/asset/svg/icn_img_logo_error.svg
  src/asset/svg/icn_safari.svg
  src/asset/svg/index.ts
  src/view/unsupported-browser/index.css.ts
  src/view/unsupported-browser/index.tsx
  tsconfig.json
Labels: ✨ Feat, WUZ, size/m

#192 [ Feat ] 그룹 생성/목록 조회/회원 목록 조회/정보 조회 API 연동
  src/api/groups/index.ts
  src/api/groups/schema.ts
  src/api/groups/type.ts
  src/api/index.ts
  src/app/[user]/page.tsx
  src/app/group/[groupId]/page.tsx
  src/app/group/[groupId]/setting/page.tsx
  src/app/layout.tsx
  src/app/provider.tsx
  src/common/component/Calendar/index.css.ts
  src/common/component/Calendar/index.tsx
  src/common/component/Carousel/index.css.ts
  src/common/component/Sidebar/index.css.ts
  src/shared/component/BrowserProvider/BrowserProvider.tsx
  src/shared/component/EditAvatar/index.tsx
  src/shared/component/Form/index.tsx
  src/shared/component/GroupInfoForm/DescFormController.tsx
  src/shared/component/GroupInfoForm/ImageFormController.tsx
  src/shared/component/GroupInfoForm/action.ts
  src/shared/component/GroupInfoForm/index.css.ts
  src/shared/component/GroupInfoForm/index.tsx
  src/view/group/setting/SettingSidebar/index.tsx
  src/view/user/create-group/CreateGroupForm/index.tsx
  src/view/user/index/GroupCard/index.tsx
  src/view/user/index/ListSection/ListSection.tsx
  src/view/user/index/constant.ts
Labels: ✨ Feat, WUZ, size/m

#203 [ Fix ] UI에서 발생하는 이슈 개선
  src/app/group/[groupId]/problem-list/page.tsx
  src/common/component/Tab/Indicator.tsx
  src/common/component/Tab/Tab.tsx
  src/view/group/dashboard/Ranking/index.tsx
  src/view/user/setting/SettingStep/index.tsx
Labels: ✨ Feat, 🐛 Fix, WUZ, size/s

#197 [ Feat ] 그룹 초대 코드 조회 API 연동 및 그룹 생성 시 초대코드 표시
  src/api/groups/index.ts
  src/api/groups/schema.ts
  src/api/index.ts
  src/app/[user]/create-group/page.tsx
  src/app/[user]/page.tsx
  src/app/group/[groupId]/page.tsx
  src/app/group/[groupId]/setting/page.tsx
  src/app/group/[groupId]/withdraw/page.tsx
  src/asset/svg/icn_copy_check.svg
  src/shared/component/CodeClipboard/index.css.ts
  src/shared/component/CodeClipboard/index.tsx
  src/shared/component/EditAvatar/index.tsx
  src/shared/component/Form/index.tsx
  src/shared/component/GroupInfoForm/ImageFormController.tsx
  src/shared/component/GroupInfoForm/action.ts
  src/shared/component/GroupInfoForm/index.tsx
  src/shared/component/GroupInfoForm/query.ts
  src/shared/component/GroupInfoForm/util.ts
  src/shared/hook/useClipboard.ts
  src/view/group/index/Withdraw/index.tsx
  src/view/group/index/WithdrawDialog/PromptWithdraw.tsx
  src/view/group/index/WithdrawDialog/SuccessWithdraw.tsx
  src/view/group/index/WithdrawDialog/index.css.ts
  src/view/group/index/WithdrawDialog/index.tsx
  src/view/group/index/WithdrawDialog/query.ts
  src/view/group/setting/SettingSidebar/index.css.ts
  src/view/group/setting/SettingSidebar/index.tsx
  src/view/user/create-group/CreateGroupForm/index.tsx
  src/view/user/create-group/LinkWithCopy/index.css.ts
  src/view/user/create-group/LinkWithCopy/index.tsx
  src/view/user/create-group/index.css.ts
Labels: ✨ Feat, WUZ, size/l

#191 [ Feat ] 그룹 코드를 사용한 그룹 정보 조회 및 참여 API 연결
  src/api/groups/index.ts
  src/api/groups/type.ts
  src/api/index.ts
  src/app/[user]/join-group/page.tsx
  src/app/[user]/layout.tsx
  src/app/join-group/[code]/action.ts
  src/app/join-group/[code]/page.tsx
  src/app/join-group/[code]/query.ts
  src/view/user/join-group/GroupInfoCard/index.tsx
  src/view/user/join-group/index.css.ts
Labels: ✨ Feat, JIN, size/m

#194 [ Feat ] 문제 생성 및 삭제 API 연결
  src/api/problems/index.ts
  src/api/problems/type.ts
  src/app/group/[groupId]/problem-list/[id]/page.tsx
  src/app/group/[groupId]/problem-list/action.ts
  src/app/group/[groupId]/problem-list/page.tsx
  src/app/group/[groupId]/problem-list/query.ts
  src/shared/component/ProblemList/Item.tsx
  src/view/group/index/ProblemSidebar/index.css.ts
  src/view/group/index/ProblemSidebar/index.tsx
  src/view/group/problem-list/ExpiredList/index.tsx
  src/view/group/problem-list/InProgressList/index.tsx
  src/view/group/problem-list/ProblemSidebar/index.tsx
  src/view/group/problem-list/RegisterForm/index.css.ts
  src/view/group/problem-list/RegisterForm/index.tsx
  src/view/group/problem-list/index.tsx
Labels: ✨ Feat, JIN, size/m

#209 [ Feat ] 공지 목록 및 하나 조회 / 생성 API 연결
  src/api/notices/index.ts
  src/api/notices/type.ts
  src/api/type.ts
  src/app/group/[groupId]/notice/[noticeId]/page.tsx
  src/app/group/[groupId]/notice/action.ts
  src/app/group/[groupId]/notice/create/page.tsx
  src/app/group/[groupId]/notice/page.tsx
  src/app/group/[groupId]/notice/query.ts
  src/app/group/[groupId]/withdraw/page.tsx
  src/common/component/Modal/Modal.tsx
  src/common/component/Modal/index.css.tsx
  src/shared/component/LoginAlertModal/index.tsx
  src/shared/util/time.ts
  src/view/group/dashboard/NoticeBanner/constant.ts
  src/view/group/dashboard/NoticeBanner/index.tsx
  src/view/group/dashboard/NoticeModal/NoticeCreate/index.tsx
  src/view/group/dashboard/NoticeModal/NoticeDetail/index.css.ts
  src/view/group/dashboard/NoticeModal/NoticeDetail/index.tsx
  src/view/group/dashboard/NoticeModal/NoticeList/index.css.ts
  src/view/group/dashboard/NoticeModal/NoticeList/index.tsx
  src/view/group/dashboard/NoticeModal/index.css.ts
  src/view/group/problem-list/ProblemSidebar/index.tsx
  src/view/group/problem-list/index.tsx
  src/view/group/setting/components/StudyDeleteModal/index.tsx
Labels: ✨ Feat, JIN, size/l

#208 [ Feat ] 알림 목록 조회 API 연결 및 알람 드롭다운 UI 일부 수정
  src/api/notifications/index.ts
  src/app/[user]/setting/page.tsx
  src/asset/svg/index.ts
  src/common/component/Menu/Menu.stories.tsx
  src/common/component/Menu/Menu.tsx
  src/shared/component/Header/Alarm.tsx
  src/shared/component/Header/Alarm/Alarm.tsx
  src/shared/component/Header/Notification/NotificationItem.css.ts
  src/shared/component/Header/Notification/NotificationItem.tsx
  src/shared/component/Header/Notification/index.css.ts
  src/shared/component/Header/Notification/index.tsx
  src/shared/component/Header/UserMenu.tsx
  src/shared/component/Header/index.tsx
  src/shared/component/Header/query.ts
  src/shared/component/Table/Table.stories.tsx
  src/shared/constant/example.ts
  src/shared/hook/useA11yHandler.ts
  src/view/user/setting/AlarmSetting/AlarmSettingTable/constant.tsx
  src/view/user/setting/AlarmSetting/AlarmSettingTable/index.tsx
  src/view/user/setting/NotificationSetting/NotificationSettingTable/constant.tsx
  src/view/user/setting/NotificationSetting/NotificationSettingTable/index.css.ts
  src/view/user/setting/NotificationSetting/NotificationSettingTable/index.tsx
  src/view/user/setting/NotificationSetting/NotificationSettingTable/type.ts
  src/view/user/setting/NotificationSetting/index.tsx
  src/view/user/setting/SettingStep/index.tsx
  src/view/user/setting/type.ts
Labels: ✨ Feat, WUZ, size/l

#206 [ Feat ] 스터디 그룹 공개 여부 수정 API 연결
  src/api/groups/index.ts
  src/api/groups/type.ts
  src/app/[user]/page.tsx
  src/app/[user]/setting/page.tsx
  src/app/join-group/[code]/query.ts
  src/shared/constant/example.ts
  src/shared/util/example.ts
  src/view/user/setting/StudyList/StudyListTable/constant.tsx
  src/view/user/setting/StudyList/StudyListTable/index.css.ts
  src/view/user/setting/StudyList/StudyListTable/type.ts
  src/view/user/setting/StudyList/index.tsx
  src/view/user/setting/StudyList/query.ts
Labels: ✨ Feat, WUZ, size/l

#217 [ Feat ] 그룹 멤버 및 그룹 삭제 API 연결 / PromptModal 구현
  src/api/comments/index.ts
  src/api/groups/index.ts
  src/api/groups/type.ts
  src/api/problems/type.ts
  src/api/solutions/index.ts
  src/api/solutions/type.ts
  src/app/[user]/page.tsx
  src/app/group/[groupId]/my-solved/page.tsx
  src/app/group/[groupId]/page.tsx
  src/app/group/[groupId]/problem-list/page.tsx
  src/app/group/[groupId]/setting/page.tsx
  src/app/group/[groupId]/setting/query.ts
  src/app/group/[groupId]/solved-detail/[id]/page.tsx
  src/asset/svg/icn_unrank.svg
  src/asset/svg/index.ts
  src/common/component/Avatar/index.tsx
  src/shared/component/CommentBox/CommentBox.stories.tsx
  src/shared/component/CommentBox/index.css.ts
  src/shared/component/CommentBox/index.tsx
  src/shared/component/ProblemList/Item.tsx
  src/shared/component/ProblemList/ProblemList.stories.tsx
  src/shared/component/PromptModal/PromptModal.stories.tsx
  src/shared/component/PromptModal/index.css.ts
  src/shared/component/PromptModal/index.tsx
  src/shared/type/comment.ts
  src/shared/type/index.ts
  src/shared/util/example.ts
  src/shared/util/img.ts
  src/shared/util/time.ts
  src/view/group/dashboard/NoticeModal/NoticeDetail/index.tsx
  src/view/group/index/WithdrawDialog/index.tsx
  src/view/group/my-solved/Section/index.tsx
  src/view/group/my-solved/SolvedItem/SolvedItem.stories.tsx
  src/view/group/my-solved/SolvedItem/index.tsx
  src/view/group/problem-list/PendingList/Item.tsx
  src/view/group/problem-list/PendingList/index.tsx
  src/view/group/problem-list/SolvedList/ProblemInfo.tsx
  src/view/group/problem-list/SolvedList/SolvedTable.tsx
  src/view/group/problem-list/SolvedList/constant.ts
  src/view/group/problem-list/index.tsx
  src/view/group/setting/MemberList/MemberListTable.tsx
  src/view/group/setting/MemberList/constant.tsx
  src/view/group/setting/MemberList/index.css.ts
  src/view/group/setting/MemberList/index.tsx
  src/view/group/setting/SettingSidebar/index.tsx
  src/view/group/solved-detail/CommentSection/index.tsx
Labels: ✨ Feat, JIN, size/xl

#215 [ Feat ] 타 유저 및 회원 정보 / 그룹 내 유저 Role 조회 API 연결
  src/api/groups/index.ts
  src/api/groups/type.ts
  src/api/index.ts
  src/api/users/index.ts
  src/api/users/type.ts
  src/app/[user]/create-group/page.tsx
  src/app/[user]/layout.tsx
  src/app/[user]/page.tsx
  src/app/[user]/setting/query.ts
  src/app/group/[groupId]/layout.tsx
  src/app/group/[groupId]/my-solved/page.tsx
  src/app/group/[groupId]/notice/page.tsx
  src/app/group/[groupId]/page.tsx
  src/shared/component/CodeClipboard/index.tsx
  src/shared/hook/useClipboard.ts
  src/view/group/dashboard/GroupSidebar/index.tsx
  src/view/group/index/MemberAvatar/index.css.tsx
  src/view/group/index/MemberAvatar/index.tsx
  src/view/group/problem-list/index.tsx
  src/view/group/setting/StudyDeleteModal/StudyDeleteModal.stories.tsx
  src/view/group/setting/StudyDeleteModal/index.css.ts
  src/view/group/setting/StudyDeleteModal/index.tsx
  src/view/user/create-group/CreateGroupForm/index.tsx
  src/view/user/index/GroupCard/index.tsx
  src/view/user/index/ListSection/ListSection.tsx
  src/view/user/index/UserCard/index.tsx
  src/view/user/setting/StudyList/StudyListTable/constant.tsx
  src/view/user/setting/StudyList/StudyListTable/type.ts
  src/view/user/setting/StudyList/index.tsx
Labels: ✨ Feat, JIN, size/m

#227 [ HotFix ] aws env 임시 토큰으로 대체
  src/api/index.ts
Labels: size/xs

#228 [ Deploy ] v0.4.0 API 연결
  src/api/index.ts
Labels: JIN, size/xs, 🚀 Deploy

#230 [ Fix ] 내 정보 불러오기 API 데이터 패칭 오류 해결
  src/shared/component/Header/Logo.tsx
  src/shared/component/Header/index.tsx
Labels: size/s

#231 [ Deploy ] v0.4.1 데이터 패칭 오류 해결
  src/shared/component/Header/Logo.tsx
  src/shared/component/Header/index.tsx
Labels: JIN, size/s, 🚀 Deploy

#232 [ Feat ] 환경변수 설정
  .github/workflows/cd-pipeline.yml
Labels: ✨ Feat, JIN, size/xs

#234 [ Fix ] 환경변수 재설정
  .github/workflows/cd-pipeline.yml
Labels: 🐛 Fix, JIN, size/xs

#235 [ Deploy ] v0.4.3 환경변수 재설정
  .github/workflows/cd-pipeline.yml
Labels: JIN, size/xs, 🚀 Deploy
