Repository GAMZA-BAT/algohub-client, pull requests merged in 2024-09, with the labels that each got.

#3 [ Init ] Biome 설정
  .github/workflows/labeler.yml
  .vscode/settings.json
  biome.json
  package.json
  pnpm-lock.yaml
Labels: 🎉 Init, JIN, size/l

#12 [ Fix ] biome 적용 안 됨 이슈 해결
  biome.json
Labels: 🐛 Fix, JIN, size/xs

#6 [ Init ] Jotai + Vanilla Extract 초기 세팅
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/components/common/Button/Button.css.ts
  src/components/common/Button/Button.tsx
  src/components/common/Provider.tsx
  src/store/auth.ts
  src/store/index.ts
Labels: 🎉 Init, WUZ, size/xl

#9 [ Init ] assets setting
  generateIconExport.js
  next.config.mjs
  package.json
  src/app/page.tsx
  src/assets/svgs/icn_active.svg
  src/assets/svgs/icn_alarm.svg
  src/assets/svgs/icn_bell_header.svg
  src/assets/svgs/icn_bell_tab.svg
  src/assets/svgs/icn_btn_arrow_down.svg
  src/assets/svgs/icn_btn_arrow_left.svg
  src/assets/svgs/icn_btn_arrow_right.svg
  src/assets/svgs/icn_btn_checkbox.svg
  src/assets/svgs/icn_btn_checkbox_fail.svg
  src/assets/svgs/icn_btn_delete_circle.svg
  src/assets/svgs/icn_btn_delete_rect.svg
  src/assets/svgs/icn_btn_list.svg
  src/assets/svgs/icn_btn_next.svg
  src/assets/svgs/icn_btn_pin.svg
  src/assets/svgs/icn_btn_plus.svg
  src/assets/svgs/icn_btn_sort.svg
  src/assets/svgs/icn_calendar_table.svg
  src/assets/svgs/icn_calender_card.svg
  src/assets/svgs/icn_check_medium.svg
  src/assets/svgs/icn_check_small.svg
  src/assets/svgs/icn_close.svg
  src/assets/svgs/icn_copy.svg
  src/assets/svgs/icn_edit.svg
  src/assets/svgs/icn_error.svg
  src/assets/svgs/icn_exit.svg
  src/assets/svgs/icn_expand_more.svg
  src/assets/svgs/icn_instagram.svg
  src/assets/svgs/icn_line.svg
  src/assets/svgs/icn_list.svg
  src/assets/svgs/icn_mail.svg
  src/assets/svgs/icn_message.svg
  src/assets/svgs/icn_my.svg
  src/assets/svgs/icn_new.svg
  src/assets/svgs/icn_notifications.svg
  src/assets/svgs/icn_pencil.svg
  src/assets/svgs/icn_plus.svg
  src/assets/svgs/icn_plus_large.svg
  src/assets/svgs/icn_search.svg
  src/assets/svgs/icn_setting.svg
  src/assets/svgs/icn_square.svg
  src/assets/svgs/icn_status_done.svg
  src/assets/svgs/icn_status_favorites.svg
  src/assets/svgs/icn_status_progress.svg
  src/assets/svgs/icn_status_queued.svg
  src/assets/svgs/icn_trash.svg
  src/assets/svgs/icn_user.svg
  src/assets/svgs/icn_user2.svg
  src/assets/svgs/icon_reset.svg
  src/assets/svgs/index.ts
  svgr.config.js
  svgr.d.ts
  tsconfig.json
Labels: 🎉 Init, GYU, size/m

#13 [ Docs ] Lint, Build, Assign Reviewer Workflow 생성
  .github/auto_assign.yml
  .github/workflows/assign-reviewer.yml
  .github/workflows/check.yml
  .github/workflows/deploy-dev.yml
  biome.json
  package.json
  pnpm-lock.yaml
  src/app/group/groupDashboard/page.tsx
  src/app/group/page.tsx
  src/app/onboarding/login/page.tsx
  src/app/onboarding/page.tsx
  src/app/onboarding/signup/page.tsx
  src/app/page.tsx
  src/app/user/page.tsx
  src/app/user/userDashboard/page.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Provider.tsx
  svgr.d.ts
Labels: 📄 Docs, size/xl

#17 [ FIX ] Add vanilaExtract setting to next.config.mjs and .nvmrc
  .nvmrc
  next.config.mjs
Labels: 🐛 Fix, 🎉 Init, size/xs

#21 [ Feat ] Toggle Button 퍼블리싱
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/components/common/Provider/Provider.tsx
  src/components/common/ToggleButton/ToggleButton.css.ts
  src/components/common/ToggleButton/ToggleButton.tsx
Labels: ✨ Feat, WUZ, size/s

#24 [ Init ] CD 파이프라인 구축
  .github/workflows/cd-pipeline.yml
  .github/workflows/ci-pipeline.yml
  .github/workflows/deploy-dev.yml
  package.json
Labels: 🎉 Init, HJO, size/m

#31 [ Feat ] header 및 드롭다운 토글 기능 구현
  biome.json
  src/app/layout.tsx
  src/assets/svgs/icn_logo.svg
  src/assets/svgs/icn_reset.svg
  src/assets/svgs/index.ts
  src/components/common/Dropdown/index.css.ts
  src/components/common/Dropdown/index.tsx
  src/components/shared/Header/LoginMenu.css.ts
  src/components/shared/Header/LoginMenu.tsx
  src/components/shared/Header/Menu.css.ts
  src/components/shared/Header/Menu.tsx
  src/components/shared/Header/Notification.css.ts
  src/components/shared/Header/Notification.tsx
  src/components/shared/Header/Profile.css.ts
  src/components/shared/Header/Profile.tsx
  src/components/shared/Header/UserMenu.tsx
  src/components/shared/Header/index.css.ts
  src/components/shared/Header/index.tsx
  src/hooks/useOutsideClick.ts
  src/utils/dom.ts
  src/utils/string.ts
Labels: ✨ Feat, GYU, size/m

#37 [ Fix ] 폴더명 대소문자 관련 CI 빌드에러 해결
  src/common/component/animation/index.tsx
  src/common/component/avatar/index.css.ts
  src/common/component/avatar/index.tsx
  src/common/component/button/index.css.ts
  src/common/component/button/index.tsx
  src/common/component/dropdown/index.css.ts
  src/common/component/dropdown/index.tsx
  src/common/component/toggleButton/index.css.ts
  src/common/component/toggleButton/index.tsx
  src/shared/component/provider/index.tsx
Labels: 🐛 Fix, JIN, size/m

#35 [ Init ] storybook 세팅 및 예시 추가(Page, Animation, Button, Dropdown)
  .github/workflows/labeler.yml
  .gitignore
  .storybook/DocsPage.tsx
  .storybook/WithAppRouterContext.tsx
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/viewport.ts
  biome.json
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/app/onboarding.stories.ts
  src/app/page.tsx
  src/common/component/Animation/Animation.stories.tsx
  src/common/component/Button/Button.stories.tsx
  src/common/component/Dropdown/Dropdown.stories.tsx
  src/common/component/Dropdown/index.tsx
  src/styles/globalStyles.css.ts
  tsconfig.json
Labels: 🎉 Init, GYU, size/l

#44 [ Feat ] Modal 공통컴포넌트 구현
  src/app/page.tsx
  src/common/component/Modal/Modal.stories.tsx
  src/common/component/Modal/index.css.tsx
  src/common/component/Modal/index.tsx
  src/common/hook/useBooleanState.ts
  src/common/hook/useOutsideClick.ts
Labels: ✨ Feat, JIN, size/m

#50 [ Feat ] Atom과 Timeout을 통한 Toast 렌더링, ToastProvider 설정
  .storybook/decorators.tsx
  .storybook/preview.ts
  src/common/component/Animation/Animation.stories.tsx
  src/common/component/Avatar/Avatar.stories.tsx
  src/common/component/Dropdown/Dropdown.stories.tsx
  src/common/component/Portal/index.tsx
  src/common/component/Toast/Toast.stories.tsx
  src/common/component/Toast/Toast.tsx
  src/common/component/Toast/index.css.ts
  src/common/component/Toast/index.tsx
  src/common/component/Toast/type.ts
  src/common/hook/useTimeout.ts
  src/common/hook/useToast.ts
  src/shared/store/toast.ts
  src/shared/type.ts
  src/shared/type/index.ts
  src/styles/animation.css.ts
  svgr.d.ts
Labels: ✨ Feat, WUZ, size/m

#51 [ Feat ] Datepicker 구현
  package.json
  pnpm-lock.yaml
  src/common/component/Calendar/Calendar.stories.tsx
  src/common/component/Calendar/index.css.ts
  src/common/component/Calendar/index.tsx
Labels: ✨ Feat, HJO, size/m
