Repository GAMZA-BAT/algohub-client, pull requests merged in 2024-12, with the labels that each got.

#241 [ Feat ] 대기 중인 문제 수정 기능 구현
  src/api/index.ts
  src/app/group/[groupId]/problem-list/action.ts
  src/app/group/[groupId]/problem-list/query.ts
  src/shared/component/ProblemList/Item.tsx
  src/shared/component/ProblemList/ProblemEdit.tsx
  src/view/group/problem-list/PendingList/Item.tsx
  src/view/group/problem-list/PendingList/index.css.ts
  src/view/group/problem-list/PendingList/index.tsx
  src/view/group/problem-list/PendingListHeader/index.css.ts
  src/view/group/problem-list/PendingListHeader/index.tsx
  src/view/group/problem-list/SolvedList/index.tsx
  src/view/group/problem-list/index.tsx
Labels: ✨ Feat, JIN, size/m

#240 [ Feat ] 그룹 탈퇴 / 수정 API 연결
  src/api/groups/index.ts
  src/api/index.ts
  src/app/group/[groupId]/setting/action.ts
  src/app/group/[groupId]/setting/page.tsx
  src/app/group/[groupId]/setting/query.ts
  src/app/group/[groupId]/withdraw/page.tsx
  src/shared/component/GroupInfoForm/index.tsx
  src/shared/component/GroupInfoForm/query.ts
  src/view/group/index/WithdrawDialog/index.tsx
  src/view/group/index/WithdrawDialog/query.ts
  src/view/group/setting/SettingSidebar/index.css.ts
  src/view/group/setting/SettingSidebar/index.tsx
  src/view/not-found/index.css.ts
Labels: ✨ Feat, WUZ, size/m

#238 [ Refactor ] 페이지네이션 깜빡임 해결
  src/api/groups/ranking.ts
  src/api/index.ts
  src/app/[user]/my-solved/page.tsx
  src/app/group/[groupId]/my-solved/page.tsx
  src/app/group/[groupId]/page.tsx
  src/app/group/[groupId]/problem-list/page.tsx
  src/shared/hook/usePaginationQuery.ts
  src/view/group/dashboard/NoticeModal/NoticeList/index.tsx
  src/view/group/dashboard/Ranking/AllRanking.tsx
  src/view/group/dashboard/Ranking/index.tsx
  src/view/group/my-solved/Section/index.tsx
  src/view/group/problem-list/PendingList/index.tsx
Labels: ♻️ Refactor, JIN, size/m

#254 [ FIX ] next-auth Session 무한 호출 에러 해결
  src/app/layout.tsx
  src/app/provider.tsx
  src/shared/component/QueryProvider/index.tsx
  src/shared/component/RefreshTokenExpireTime/index.tsx
Labels: 🐛 Fix, WUZ, size/s

#259 [ Fix ] 필터링 오류 수정
  src/app/[user]/setting/query.ts
  src/view/user/setting/StudyList/StudyListTable/StudyListProvider.tsx
  src/view/user/setting/StudyList/StudyListTable/constant.tsx
  src/view/user/setting/StudyList/StudyListTable/hook.ts
Labels: 🐛 Fix, GYU, size/s

#244 [ Feat ] 그룹 멤버 역할 수정 API 연결
  src/app/api/groups/index.ts
  src/app/api/groups/type.ts
  src/app/group/[groupId]/setting/action.ts
  src/app/group/[groupId]/setting/page.tsx
  src/app/group/[groupId]/setting/query.ts
  src/app/join-group/[code]/query.ts
  src/view/group/setting/MemberList/MemberListProvider.tsx
  src/view/group/setting/MemberList/RoleList/RoleChip.tsx
  src/view/group/setting/MemberList/RoleList/RoleDropdownMenu.tsx
  src/view/group/setting/MemberList/RoleList/index.css.ts
  src/view/group/setting/MemberList/constant.tsx
  src/view/group/setting/SettingSidebar/index.tsx
Labels: ✨ Feat, JIN, size/m

#260 [ Feat ] 그룹 및 알림 설정 API 연결
  src/app/[user]/page.tsx
  src/app/[user]/query.ts
  src/app/[user]/setting/page.tsx
  src/app/[user]/setting/query.ts
  src/app/api/groups/index.ts
  src/app/api/groups/type.ts
  src/app/api/notifications/index.ts
  src/app/api/notifications/type.ts
  src/asset/svg/icn_status_done.svg
  src/asset/svg/icn_status_favorites.svg
  src/asset/svg/icn_status_progress.svg
  src/asset/svg/icn_status_queued.svg
  src/asset/svg/index.ts
  src/shared/component/Table/Table.stories.tsx
  src/shared/constant/example.ts
  src/view/group/setting/MemberList/RoleList/RoleDropdownMenu.tsx
  src/view/group/setting/MemberList/constant.tsx
  src/view/user/index/GroupCard/StatusDot.tsx
  src/view/user/index/GroupCard/StatusIcon.tsx
  src/view/user/index/GroupCard/index.css.ts
  src/view/user/index/GroupCard/index.tsx
  src/view/user/index/ListSection/ListSection.tsx
  src/view/user/setting/GroupList/GroupListTable/GroupListProvider.tsx
  src/view/user/setting/GroupList/GroupListTable/constant.tsx
  src/view/user/setting/GroupList/GroupListTable/hook.ts
  src/view/user/setting/GroupList/GroupListTable/index.css.ts
  src/view/user/setting/GroupList/GroupListTable/index.tsx
  src/view/user/setting/GroupList/GroupListTable/type.ts
  src/view/user/setting/GroupList/SortIcon/index.css.ts
  src/view/user/setting/GroupList/SortIcon/index.tsx
  src/view/user/setting/GroupList/StatusDropdownMenu/index.css.ts
  src/view/user/setting/GroupList/StatusDropdownMenu/index.tsx
  src/view/user/setting/GroupList/StatusIcon/index.css.ts
  src/view/user/setting/GroupList/StatusIcon/index.tsx
  src/view/user/setting/GroupList/index.css.ts
  src/view/user/setting/GroupList/index.tsx
  src/view/user/setting/NotificationSetting/NotificationSettingTable/constant.tsx
  src/view/user/setting/NotificationSetting/NotificationSettingTable/index.css.ts
  src/view/user/setting/NotificationSetting/NotificationSettingTable/index.tsx
  src/view/user/setting/NotificationSetting/NotificationSettingTable/type.ts
  src/view/user/setting/StudyList/StatusIcon/index.tsx
  src/view/user/setting/StudyList/index.tsx
Labels: ✨ Feat, JIN, size/xl

#256 [ Feat ] Notification 전체/단건 읽음 API 연결
  src/app/api/notices/type.ts
  src/app/api/notifications/index.ts
  src/app/api/notifications/type.ts
  src/app/api/solutions/type.ts
  src/shared/component/CommentBox/CommentBox.stories.tsx
  src/shared/component/CommentBox/index.css.ts
  src/shared/component/CommentBox/index.tsx
  src/shared/component/Header/Notification/NotificationItem.css.ts
  src/shared/component/Header/Notification/NotificationItem.tsx
  src/shared/component/Header/Notification/index.css.ts
  src/shared/component/Header/Notification/index.tsx
  src/shared/component/Header/query.ts
  src/shared/component/SolvedFilterBar/index.tsx
  src/shared/constant/solvedFilterKey.ts
  src/shared/type/comment.ts
  src/shared/type/solvedFilter.ts
  src/shared/util/time.ts
  src/view/group/dashboard/NoticeBanner/index.tsx
  src/view/group/dashboard/NoticeModal/NoticeDetail/index.tsx
  src/view/group/dashboard/NoticeModal/NoticeList/index.tsx
  src/view/group/solved-detail/CodeSection/CodeHighlighter/CodeHighlighter.tsx
  src/view/group/solved-detail/CodeSection/CodeHighlighter/rule.ts
  src/view/group/solved-detail/CodeSection/index.tsx
Labels: ✨ Feat, WUZ, size/m

#257 [ Feat ] 스터디 공개 여부 수정 / 알림 읽음 Mutation 시 낙관적 업데이트 적용
  src/app/[user]/setting/query.ts
  src/app/query.ts
  src/shared/component/Header/Notification/index.css.ts
  src/shared/component/Header/Notification/index.tsx
  src/shared/component/Header/UserMenu.tsx
  src/shared/component/Header/query.ts
Labels: ✨ Feat, WUZ, size/m

#262 [ Feat ] inProgress unsolved-only 파라미터 추가
  src/app/api/problems/index.ts
  src/app/api/problems/type.ts
  src/app/group/[groupId]/problem-list/page.tsx
Labels: ✨ Feat, JIN, size/s

#265 [ Fix ] nextAuth 배포 에러 해결
  src/auth.ts
Labels: 🐛 Fix, JIN, size/xs

#266 [ Deploy ] 0.4.5 nextAuth 배포 에러 해결
  src/auth.ts
Labels: JIN, size/xs, 🚀 Deploy

#274 [ Fix ] Form의 default image 표시
  src/shared/component/Form/index.tsx
  src/view/group/setting/SettingSidebar/index.css.ts
  src/view/group/setting/SettingSidebar/index.tsx
Labels: 🐛 Fix, GYU, size/s

#261 [ Feat ] Unsolved Problem 필터링 API 반영
  src/app/api/problems/index.ts
  src/app/api/problems/type.ts
  src/app/group/[groupId]/problem-list/page.tsx
  src/app/group/[groupId]/problem-list/query.ts
  src/shared/component/ProblemList/index.css.ts
  src/shared/hook/usePaginationQuery.ts
  src/view/group/dashboard/ProblemListHeader/index.css.ts
  src/view/group/problem-list/ProblemSection/index.tsx
  src/view/group/problem-list/index.css.ts
Labels: ✨ Feat, WUZ, size/m

#268 [ Fix ] DatePicker와 SolvedSection 타이틀 레이아웃 시프트 해결
  src/common/component/Calendar/index.css.ts
  src/shared/component/GroupInfoForm/index.tsx
Labels: 🐛 Fix, WUZ, size/s

#270 [ Fix ] 코멘트 뷰 유저에 따른 UI 미반영 사항들 적용
  src/shared/component/CommentBox/index.tsx
  src/shared/component/Header/UserMenu.tsx
  src/view/group/solved-detail/CommentSection/index.tsx
Labels: 🐛 Fix, WUZ, size/s

#277 [ Fix ] 유저 대쉬보드, 마이페이지 두 번 로딩되는 이슈 해결
  src/app/[user]/page.tsx
  src/asset/lottie/spinner.json
  src/common/component/Spinner/index.css.ts
  src/common/component/Spinner/index.tsx
  src/shared/component/GroupInfoForm/action.ts
  src/view/user/setting/GroupList/GroupListTable/GroupListProvider.tsx
  src/view/user/setting/GroupList/index.css.ts
  src/view/user/setting/GroupList/index.tsx
  src/view/user/setting/NotificationSetting/NotificationSettingTable/index.tsx
  src/view/user/setting/NotificationSetting/index.tsx
  src/view/user/setting/loading.tsx
Labels: 🐛 Fix, WUZ, size/m
