Repository GAMZA-BAT/algohub-client, pull requests merged in 2024-10, with the labels that each got.

#46 [ Feat ] Context를 통한 TabGroup 컴파운드 컴포넌트 구현
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/common/component/Tab/Indicator.tsx
  src/common/component/Tab/Tab.tsx
  src/common/component/Tab/TabList.tsx
  src/common/component/Tab/TabPanels.tsx
  src/common/component/Tab/TabProvider.tsx
  src/common/component/Tab/Tabs.stories.tsx
  src/common/component/Tab/Tabs.tsx
  src/common/component/Tab/index.css.ts
  src/common/component/Tab/index.tsx
  src/styles/globalStyles.css.ts
Labels: ✨ Feat, WUZ, size/m

#64 [ Refactor ] 모든 파일 일괄 포매터 적용 및 CI 설정
  .storybook/DocsPage.tsx
  .storybook/viewport.ts
  biome.json
  package.json
  src/app/onboarding.stories.ts
  src/asset/svg/index.ts
  src/common/component/Avatar/index.css.ts
  src/common/component/Button/Button.stories.tsx
  src/common/component/Button/index.css.ts
  src/common/component/Calendar/index.css.ts
  src/common/component/Calendar/index.tsx
  src/common/component/Dropdown/index.css.ts
  src/common/component/Dropdown/index.tsx
  src/common/component/Modal/index.tsx
  src/common/hook/useBooleanState.ts
  src/common/hook/useOutsideClick.ts
  src/common/hook/useTimeout.ts
  src/common/hook/useToast.ts
  src/common/util/dom.ts
  src/common/util/string.ts
  src/shared/component/Header/Alarm.css.ts
  src/shared/component/Header/Alarm.tsx
  src/shared/component/Header/AlarmListItem.css.ts
  src/shared/component/Header/AlarmListItem.tsx
  src/shared/component/Header/LoginMenu.css.ts
  src/shared/component/Header/Menu.css.ts
  src/shared/component/Header/Profile.css.ts
  src/shared/constant/example.ts
Labels: ♻️ Refactor, HJO, size/m

#71 [ Fix ] Format-on-save가 정상 작동하게 수정
  .vscode/settings.json
  src/common/component/Tab/index.tsx
Labels: 🐛 Fix, HJO, size/s

#38 [ Feat ] Add common-input component
  src/common/component/Input/Input.stories.tsx
  src/common/component/Input/index.css.ts
  src/common/component/Input/index.tsx
  src/common/component/SupportingText/Index.css.ts
  src/common/component/SupportingText/SupportingText.stories.tsx
  src/common/component/SupportingText/index.tsx
  src/common/component/Textarea/Textarea.stories.tsx
  src/common/component/Textarea/index.css.ts
  src/common/component/Textarea/index.tsx
  src/styles/themes.css.ts
Labels: ✨ Feat, HJO, size/m

#66 [ Feat ] EditAvatar 구현 + storybook
  src/app/layout.tsx
  src/app/page.tsx
  src/asset/svg/icn_edit_profile.svg
  src/asset/svg/index.ts
  src/common/component/Avatar/index.css.ts
  src/common/component/Avatar/index.tsx
  src/common/component/Input/index.tsx
  src/common/component/Textarea/index.tsx
  src/shared/component/EditAvatar/EditAvatar.stories.tsx
  src/shared/component/EditAvatar/index.css.ts
  src/shared/component/EditAvatar/index.tsx
Labels: ✨ Feat, JIN, size/m

#62 [ Feat ] pagination component 구현
  src/shared/component/Pagination/Pagination.stories.tsx
  src/shared/component/Pagination/Pagination.tsx
  src/shared/component/Pagination/index.css.ts
  src/shared/component/Pagination/index.tsx
  src/shared/util/pagination.ts
Labels: ✨ Feat, GYU, size/m

#57 [ Feat ] Form 공통 컴포넌트 구현
  .storybook/decorators.tsx
  package.json
  pnpm-lock.yaml
  src/common/component/Calendar/index.tsx
  src/common/component/Input/index.tsx
  src/common/component/SupportingText/index.tsx
  src/shared/api/validate.ts
  src/shared/component/Form/Form.stories.tsx
  src/shared/component/Form/FormDescription.tsx
  src/shared/component/Form/FormLabel.tsx
  src/shared/component/Form/index.css.ts
  src/shared/component/Form/index.tsx
  src/shared/hook/.gitkeep
  src/shared/hook/useCheckOnServer.ts
  src/shared/util/.gitkeep
  src/shared/util/form.ts
Labels: ✨ Feat, 📄 Docs, GYU, size/l

#85 [ Style ] Button 디자인 마이그레이션
  src/common/component/Button/Button.stories.tsx
  src/common/component/Button/index.css.ts
  src/common/component/Button/index.tsx
Labels: 💄 Style, JIN, size/s

#67 [ Feat ] Sidebar 컴포넌트 구현 및 탭 Icon prop 방식 수정
  src/app/group/page.tsx
  src/common/component/Sidebar/index.css.ts
  src/common/component/Sidebar/index.tsx
  src/common/component/Tab/Tab.tsx
  src/common/component/Tab/TabList.tsx
  src/common/component/Tab/TabPanels.tsx
  src/common/component/Tab/TabProvider.tsx
  src/common/component/Tab/Tabs.stories.tsx
  src/common/component/Tab/Tabs.tsx
  src/common/component/Tab/index.css.ts
Labels: ✨ Feat, WUZ, size/m

#84 [ Feat ] profile image type 추가 및 field props 통합
  src/common/component/Textarea/index.tsx
  src/shared/component/EditAvatar/index.tsx
  src/shared/component/Form/Form.stories.tsx
  src/shared/component/Form/index.css.ts
  src/shared/component/Form/index.tsx
Labels: ✨ Feat, GYU, size/m

#75 [ Feat ] JoinGroup 퍼블리싱
  src/app/user/join-group/page.tsx
  src/asset/svg/group_info_card.svg
  src/asset/svg/icn_btn_delete.svg
  src/asset/svg/index.ts
  src/common/component/Modal/index.css.tsx
  src/common/component/Modal/index.tsx
  src/view/user/join-group/api/.gitkeep
  src/view/user/join-group/api/type.ts
  src/view/user/join-group/component/.gitkeep
  src/view/user/join-group/component/DecisionPrompt/index.css.ts
  src/view/user/join-group/component/DecisionPrompt/index.tsx
  src/view/user/join-group/component/GroupInfoCard/GroupDateInfo.css.ts
  src/view/user/join-group/component/GroupInfoCard/GroupDateInfo.tsx
  src/view/user/join-group/component/GroupInfoCard/index.css.ts
  src/view/user/join-group/component/GroupInfoCard/index.tsx
  src/view/user/join-group/component/index.css.ts
Labels: ✨ Feat, JIN, size/m

#92 [ Refactor ] api 폴더구조 리팩토링
  README.md
  src/api/board/type.ts
  src/api/comment/type.ts
  src/api/group/type.ts
  src/api/index.ts
  src/api/notification/type.ts
  src/api/problem/type.ts
  src/api/solution/type.ts
  src/api/user/type.ts
  src/api/validate.ts
  src/app/user/join-group/page.tsx
  src/shared/component/Form/Form.stories.tsx
  src/shared/hook/useCheckOnServer.ts
  src/view/group/problem-list/api/.gitkeep
  src/view/group/setting/api/.gitkeep
  src/view/group/solved-list/api/.gitkeep
  src/view/user/create-group/api/.gitkeep
  src/view/user/index/api/.gitkeep
  src/view/user/join-group/component/GroupInfoCard/index.tsx
Labels: ♻️ Refactor, JIN, size/s

#87 [ Feat ] Problem List Item 컴포넌트 퍼블리싱
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/common/component/CheckBox/CheckBox.stories.tsx
  src/common/component/CheckBox/index.css.ts
  src/common/component/CheckBox/index.tsx
  src/shared/component/ProblemList/Item.tsx
  src/shared/component/ProblemList/ProblemList.stories.tsx
  src/shared/component/ProblemList/img.ts
  src/shared/component/ProblemList/index.css.ts
  src/shared/component/ProblemList/index.tsx
  src/shared/type/index.ts
Labels: ✨ Feat, WUZ, size/m

#90 [ Feat ] 라우트 이동을 관리하는 NavBar 컴포넌트 퍼블리싱
  src/app/group/layout.tsx
  src/app/layout.tsx
  src/shared/component/NavBar/Item.tsx
  src/shared/component/NavBar/NavBar.stories.tsx
  src/shared/component/NavBar/index.css.ts
  src/shared/component/NavBar/index.tsx
Labels: ✨ Feat, WUZ, size/m

#93 [ Feat ] Login page 구현
  src/app/login/page.tsx
  src/view/index/component/.gitkeep
  src/view/index/component/AuthHeader/index.css.ts
  src/view/index/component/AuthHeader/index.tsx
  src/view/index/component/Card/index.css.ts
  src/view/index/component/Card/index.tsx
  src/view/index/component/Footer/index.css.ts
  src/view/index/component/Footer/index.tsx
  src/view/index/component/SubmitButton/index.css.ts
  src/view/index/component/SubmitButton/index.tsx
  src/view/login/api/schema.ts
  src/view/login/component/.gitkeep
  src/view/login/component/Container/index.css.ts
  src/view/login/component/Container/index.tsx
  src/view/login/component/Heading/index.css.ts
  src/view/login/component/Heading/index.tsx
  src/view/login/component/LoginForm/index.css.ts
  src/view/login/component/LoginForm/index.tsx
  src/view/login/component/index.css.ts
  src/view/login/hook/useLoginForm.ts
Labels: ✨ Feat, GYU, size/m

#96 [ Feat ] favicon 설정
  public/favicon.png
  src/app/layout.tsx
Labels: ✨ Feat, JIN, size/xs

#103 [ Fix ] onboarding-section3의 이미지 레이아웃 문제 해결
  src/styles/globalStyles.css.ts
  src/view/onboarding/Section/index.css.ts
  src/view/onboarding/Section/index.tsx
Labels: 🐛 Fix, GYU, size/s

#110 [ Fix ] onboarding section1, 폴더 구조
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/user/create-group/page.tsx
  src/app/user/layout.tsx
  src/app/user/setting/layout.tsx
  src/common/component/Animation/Animation.tsx
  src/common/component/Animation/index.tsx
  src/common/component/Modal/Modal.stories.tsx
  src/common/component/Modal/Modal.tsx
  src/common/component/Modal/index.tsx
  src/shared/component/Header/LoginMenu.tsx
  src/styles/globalStyles.css.ts
  src/view/login/LoginForm/index.css.ts
  src/view/login/LoginForm/index.tsx
  src/view/login/LoginForm/schema.ts
  src/view/login/LoginForm/useLoginForm.ts
  src/view/login/component/Container/index.css.ts
  src/view/login/component/Container/index.tsx
  src/view/login/component/Heading/index.css.ts
  src/view/login/component/Heading/index.tsx
  src/view/login/index.css.ts
  src/view/onboarding/Section/Section1.tsx
  src/view/onboarding/Section/index.css.ts
  src/view/onboarding/Section/index.tsx
  src/view/user/create-group/CreateGroupForm/index.css.ts
  src/view/user/create-group/CreateGroupForm/index.tsx
  src/view/user/create-group/LinkWithCopy/index.css.ts
  src/view/user/create-group/LinkWithCopy/index.tsx
  src/view/user/create-group/index.css.ts
  src/view/user/setting/StatusDropdownMenu/index.css.ts
  src/view/user/setting/StatusDropdownMenu/index.tsx
  src/view/user/setting/StatusIcon/index.tsx
  src/view/user/setting/constant.tsx
Labels: 🐛 Fix, GYU, size/m

#113 [ Feat ] instagram, mail 링크 추가
  src/shared/component/GroupInfoForm/index.tsx
  src/view/onboarding/Footer/index.tsx
Labels: ✨ Feat, JIN, size/s

#100 [ Feat ] UserPage - Dashboard 퍼블리싱
  src/api/user/type.ts
  src/app/user/layout.tsx
  src/app/user/page.tsx
  src/asset/img/img_card_profile.png
  src/asset/svg/icn_calender_card.svg
  src/common/component/Calendar/index.css.ts
  src/common/component/Carousel/index.css.ts
  src/common/component/Carousel/index.tsx
  src/shared/type/table.ts
  src/shared/util/example.ts
  src/styles/shared.css.ts
  src/view/group/dashboard/GroupSidebar/GroupCard/index.css.ts
  src/view/group/dashboard/GroupSidebar/GroupCard/index.tsx
  src/view/user/index/GroupCard/StatusIcon.tsx
  src/view/user/index/GroupCard/index.css.ts
  src/view/user/index/GroupCard/index.tsx
  src/view/user/index/constant.ts
  src/view/user/index/index.css.ts
  src/view/user/index/type.ts
  src/view/user/join-group/GroupInfoCard/GroupDateInfo.css.ts
  src/view/user/setting/StatusIcon/index.tsx
Labels: ✨ Feat, JIN, size/l

#119 [ Feat ] my page - 계정 관리 탭 구현
  src/app/user/setting/page.tsx
  src/view/user/setting/AccountManagement/index.css.ts
  src/view/user/setting/AccountManagement/index.tsx
  src/view/user/setting/AccountManagementForm/index.css.ts
  src/view/user/setting/AccountManagementForm/index.tsx
  src/view/user/setting/AccountManagementForm/schema.ts
  src/view/user/setting/AccountManagementForm/useAccountForm.ts
Labels: ✨ Feat, GYU, size/m

#123 [ Feat ] my page - study 관리 탭 구현
  src/app/user/layout.tsx
  src/app/user/setting/page.tsx
  src/common/component/Menu/Menu.tsx
  src/shared/component/Table/Table.stories.tsx
  src/shared/component/Table/TableElements/Body.tsx
  src/shared/component/Table/TableElements/index.css.ts
  src/shared/component/Table/index.css.ts
  src/shared/constant/example.ts
  src/shared/type/table.ts
  src/view/user/setting/StatusDropdownMenu/index.tsx
  src/view/user/setting/StudyList/SortIcon/index.css.ts
  src/view/user/setting/StudyList/SortIcon/index.tsx
  src/view/user/setting/StudyList/StatusDropdownMenu/index.css.ts
  src/view/user/setting/StudyList/StatusDropdownMenu/index.tsx
  src/view/user/setting/StudyList/StatusIcon/index.tsx
  src/view/user/setting/StudyList/StudyListTable/StudyListProvider.tsx
  src/view/user/setting/StudyList/StudyListTable/StudyListTable.tsx
  src/view/user/setting/StudyList/StudyListTable/constant.tsx
  src/view/user/setting/StudyList/StudyListTable/hook.ts
  src/view/user/setting/StudyList/index.css.ts
  src/view/user/setting/StudyList/index.tsx
  src/view/user/setting/constant.tsx
Labels: ✨ Feat, GYU, size/l

#117 [ Feat ] Comment Box, Input 컴포넌트 퍼블리싱
  src/asset/svg/icn_btn_send.svg
  src/asset/svg/icn_group_info_card.svg
  src/asset/svg/index.ts
  src/shared/component/CommentBox/CommentBox.stories.tsx
  src/shared/component/CommentBox/index.css.ts
  src/shared/component/CommentBox/index.tsx
  src/shared/component/CommentInput/CommentInput.stories.tsx
  src/shared/component/CommentInput/index.css.ts
  src/shared/component/CommentInput/index.tsx
  src/shared/type/comment.ts
  src/shared/util/time.ts
Labels: ✨ Feat, WUZ, size/m

#131 [ Docs ] defaultImg 및 setting step bar 수정
  src/shared/component/EditAvatar/index.tsx
  src/view/user/setting/SettingStep/index.css.ts
Labels: 💄 Style, 📄 Docs, JIN, size/s

#104 [ Feat ] Group Ranking 퍼블리싱
  src/api/group/schema.ts
  src/api/group/type.ts
  src/app/group/page.tsx
  src/asset/svg/icn_mini_logo.svg
  src/asset/svg/icn_ranking_card.svg
  src/asset/svg/icn_ranking_card_hover.svg
  src/asset/svg/index.ts
  src/common/component/Avatar/index.tsx
  src/common/component/Tab/index.css.ts
  src/shared/component/GroupInfoForm/index.tsx
  src/shared/constant/example.ts
  src/shared/type/index.ts
  src/styles/globalStyles.css.ts
  src/view/group/dashboard/Ranking/AllRanking.tsx
  src/view/group/dashboard/Ranking/RankList.tsx
  src/view/group/dashboard/Ranking/RankingCard.tsx
  src/view/group/dashboard/Ranking/TopRanking.tsx
  src/view/group/dashboard/Ranking/index.css.ts
  src/view/group/dashboard/Ranking/index.tsx
  src/view/group/dashboard/index.css.ts
  src/view/user/create-group/.gitkeep
  src/view/user/create-group/CreateGroupForm/index.tsx
  src/view/user/setting/component/SettingStep/index.css.ts
  src/view/user/setting/component/SettingStep/index.tsx
Labels: ✨ Feat, JIN, size/l

#137 [ Docs ] API Type 지정
  src/api/board/type.ts
  src/api/comment/type.ts
  src/api/group/type.ts
  src/api/notice/type.ts
  src/api/notification/type.ts
  src/api/problem/type.ts
  src/api/solution/type.ts
  src/api/user/type.ts
  src/app/user/page.tsx
  src/shared/constant/example.ts
  src/shared/type/table.ts
  src/shared/util/example.ts
  src/view/group/dashboard/GroupSidebar/GroupCard/index.tsx
  src/view/group/dashboard/GroupSidebar/index.tsx
  src/view/group/dashboard/Ranking/AllRanking.tsx
  src/view/group/dashboard/Ranking/RankList.tsx
  src/view/group/dashboard/Ranking/RankingCard.tsx
  src/view/group/dashboard/Ranking/TopRanking.tsx
  src/view/user/index/GroupCard/StatusIcon.tsx
  src/view/user/index/GroupCard/index.tsx
  src/view/user/setting/StudyList/StatusIcon/index.tsx
Labels: 📄 Docs, JIN, size/m

#134 [ Style ] Calendar 스타일 조정
  src/common/component/Calendar/index.css.ts
  src/common/component/Calendar/index.tsx
Labels: 💄 Style, HJO, size/s

#132 [ Feat ] my page - alarm setting 탭 구현
  src/app/user/layout.tsx
  src/app/user/setting/page.tsx
  src/shared/component/Table/Table.stories.tsx
  src/shared/component/Table/TableElements/Header.tsx
  src/shared/component/Table/TableElements/index.css.ts
  src/shared/constant/example.ts
  src/shared/type/table.ts
  src/view/user/setting/AccountManagement/AccountManagementForm/index.css.ts
  src/view/user/setting/AccountManagement/AccountManagementForm/index.tsx
  src/view/user/setting/AccountManagement/AccountManagementForm/schema.ts
  src/view/user/setting/AccountManagement/AccountManagementForm/useAccountForm.ts
  src/view/user/setting/AccountManagement/index.tsx
  src/view/user/setting/AlarmSetting/AlarmSettingTable/constant.tsx
  src/view/user/setting/AlarmSetting/AlarmSettingTable/index.css.ts
  src/view/user/setting/AlarmSetting/AlarmSettingTable/index.tsx
  src/view/user/setting/AlarmSetting/AlarmSettingTable/type.ts
  src/view/user/setting/AlarmSetting/index.tsx
  src/view/user/setting/MyProfile/EditForm/index.css.ts
  src/view/user/setting/MyProfile/EditForm/index.tsx
  src/view/user/setting/MyProfile/EditForm/schema.ts
  src/view/user/setting/MyProfile/EditForm/useEditForm.ts
  src/view/user/setting/MyProfile/index.tsx
  src/view/user/setting/StudyList/StudyListTable/StudyListProvider.tsx
  src/view/user/setting/StudyList/StudyListTable/constant.tsx
  src/view/user/setting/StudyList/StudyListTable/index.tsx
  src/view/user/setting/StudyList/StudyListTable/type.ts
  src/view/user/setting/StudyList/index.tsx
  src/view/user/setting/component/SettingStep/index.css.ts
  src/view/user/setting/component/SettingStep/index.tsx
  src/view/user/setting/constant.tsx
  src/view/user/setting/index.css.ts
Labels: ✨ Feat, GYU, size/m

#106 [ Feat ] Withdraw Modal 퍼블리싱
  src/app/group/layout.tsx
  src/app/group/withdraw/page.tsx
  src/common/component/Modal/index.css.tsx
  src/view/group/index/Withdraw/PromptWithdraw.tsx
  src/view/group/index/Withdraw/SuccessWithdraw.tsx
  src/view/group/index/Withdraw/index.css.ts
  src/view/group/index/Withdraw/index.tsx
Labels: ✨ Feat, JIN, size/m

#122 [ Feat ] Item 컴포넌트에 수정 기능 Edit 아이콘 추가
  src/common/component/CheckBox/index.tsx
  src/shared/component/ProblemList/Item.tsx
  src/shared/component/ProblemList/ProblemList.stories.tsx
  src/shared/component/ProblemList/index.css.ts
Labels: ✨ Feat, WUZ, size/m

#142 [ Feat ] notice banner 및 공지 리스트 모달
  src/app/group/page.tsx
  src/common/component/Tab/TabPanels.tsx
  src/shared/util/time.ts
  src/styles/themes.css.ts
  src/view/group/dashboard/NoticeBanner/constant.ts
  src/view/group/dashboard/NoticeBanner/index.css.ts
  src/view/group/dashboard/NoticeBanner/index.tsx
  src/view/group/dashboard/NoticeModal/index.css.ts
  src/view/group/dashboard/NoticeModal/index.tsx
  src/view/group/dashboard/index.css.ts
Labels: ✨ Feat, GYU, size/m

#146 [ Feat ] 공지 상세 보기, 수정/삭제 퍼블리싱
  src/api/notice/type.ts
  src/view/group/dashboard/NoticeBanner/constant.ts
  src/view/group/dashboard/NoticeBanner/index.css.ts
  src/view/group/dashboard/NoticeBanner/index.tsx
  src/view/group/dashboard/NoticeModal/NoticeDetail/index.css.ts
  src/view/group/dashboard/NoticeModal/NoticeDetail/index.tsx
  src/view/group/dashboard/NoticeModal/NoticeList/index.css.ts
  src/view/group/dashboard/NoticeModal/NoticeList/index.tsx
  src/view/group/dashboard/NoticeModal/index.css.ts
  src/view/group/dashboard/NoticeModal/index.tsx
  src/view/group/dashboard/index.css.ts
Labels: ✨ Feat, GYU, size/l

#138 [ Feat ] Dashboard 풀어야 할 문제와 전체 페이지 퍼블리싱
  src/app/group/page.css.ts
  src/app/group/page.tsx
  src/shared/component/ProblemList/Item.tsx
  src/shared/component/ProblemList/index.css.ts
  src/shared/component/ProblemList/index.tsx
  src/view/group/dashboard/ProblemListHeader/index.css.ts
  src/view/group/dashboard/ProblemListHeader/index.tsx
Labels: ✨ Feat, WUZ, size/m

#144 [ Style ] Modal background 제거
  src/app/user/create-group/page.tsx
  src/app/user/join-group/page.tsx
  src/view/user/setting/MyProfile/index.css.ts
Labels: 💄 Style, JIN, size/s

#159 [ Init ] Deploy pr도 CI돌게 변경
  .github/workflows/ci-pipeline.yml
Labels: 🎉 Init, HJO, size/xs

#152 [ Fix ] table 스타일링 방식 변경
  src/shared/component/Table/Table.stories.tsx
  src/shared/component/Table/TableElements/Body.tsx
  src/shared/component/Table/TableElements/Header.tsx
  src/shared/component/Table/TableElements/TableCell.tsx
  src/shared/component/Table/TableElements/TableHead.tsx
  src/shared/component/Table/TableElements/index.css.ts
  src/shared/component/Table/index.tsx
  src/shared/type/table.ts
  src/view/user/setting/AlarmSetting/AlarmSettingTable/index.css.ts
  src/view/user/setting/AlarmSetting/AlarmSettingTable/index.tsx
  src/view/user/setting/StudyList/StudyListTable/constant.tsx
  src/view/user/setting/StudyList/StudyListTable/index.css.ts
  src/view/user/setting/StudyList/StudyListTable/index.tsx
Labels: 🐛 Fix, GYU, size/m

#153 [ Feat ] SelectBox 구현
  src/common/component/SelectBox/SelectBox.stories.tsx
  src/common/component/SelectBox/index.css.ts
  src/common/component/SelectBox/index.tsx
  src/shared/constant/solvedResult.ts
Labels: ✨ Feat, JIN, size/m

#149 [ Init ] Ky 세팅 및 서버 통신 이상유무 확인
  .gitignore
  package.json
  pnpm-lock.yaml
  src/api/board/index.ts
  src/api/index.ts
  src/api/user/signIn/index.ts
  src/api/user/type.ts
Labels: 🎉 Init, WUZ, size/s

#155 [ Feat ] Notice 모달 Detail의 코멘트 부분 퍼블리싱
  src/app/group/page.tsx
  src/shared/component/CommentBox/index.tsx
  src/view/group/dashboard/NoticeModal/NoticeDetail/index.css.ts
  src/view/group/dashboard/NoticeModal/NoticeDetail/index.tsx
  src/view/group/dashboard/NoticeModal/index.css.ts
Labels: ✨ Feat, WUZ, size/s

#164 [ Feat ] 스터디 Delete modal 퍼블리싱
  src/common/component/Modal/index.css.tsx
  src/view/group/setting/components/StudyDeleteModal/StudyDeleteModal.stories.tsx
  src/view/group/setting/components/StudyDeleteModal/index.css.ts
  src/view/group/setting/components/StudyDeleteModal/index.tsx
Labels: ✨ Feat, WUZ, size/s

#165 [ Feat ] Login 필요 가이드 모달 퍼블리싱
  src/shared/component/LoginAlertModal/LoginAlertModal.stories.tsx
  src/shared/component/LoginAlertModal/index.css.ts
  src/shared/component/LoginAlertModal/index.tsx
Labels: ✨ Feat, WUZ, size/s

#108 [ Feat ] 문제 생성 및 수정 모달 퍼블리싱
  src/app/group/problem-list/page.tsx
  src/asset/lottie/index.ts
  src/asset/lottie/problem_register.json
  src/view/group/index/ProblemSidebar/index.tsx
  src/view/group/problem-list/.gitkeep
  src/view/group/problem-list/RegisterForm/DateFormController.tsx
  src/view/group/problem-list/RegisterForm/LinkFormController.tsx
  src/view/group/problem-list/RegisterForm/index.css.ts
  src/view/group/problem-list/RegisterForm/index.tsx
  src/view/group/problem-list/RegisterForm/schema.ts
Labels: ✨ Feat, JIN, size/m

#168 [ Feat ] Problemlist 페이지 퍼블리싱
  src/app/group/layout.tsx
  src/app/group/my-solved/page.tsx
  src/app/group/problem-list/page.tsx
  src/view/group/my-solved/Section/index.css.ts
  src/view/group/my-solved/Section/index.tsx
  src/view/group/problem-list/ExpiredList/index.tsx
  src/view/group/problem-list/InProgressList/index.tsx
  src/view/group/problem-list/PendingList/Item.tsx
  src/view/group/problem-list/PendingList/index.css.ts
  src/view/group/problem-list/PendingList/index.tsx
  src/view/group/problem-list/PendingListHeader/index.css.ts
  src/view/group/problem-list/PendingListHeader/index.tsx
  src/view/group/problem-list/index.css.ts
Labels: ✨ Feat, WUZ, size/m

#145 [ Feat ] GroupPage Setting 구현
  src/app/group/setting/page.tsx
  src/asset/img/small_logo.png
  src/common/component/Avatar/index.tsx
  src/shared/component/EditAvatar/index.tsx
  src/shared/hook/useA11yHandler.ts
  src/shared/util/example.ts
  src/view/group/dashboard/Ranking/RankList.tsx
  src/view/group/setting/.gitkeep
  src/view/group/setting/MemberList/MemberListProvider.tsx
  src/view/group/setting/MemberList/MemberListTable.tsx
  src/view/group/setting/MemberList/constant.tsx
  src/view/group/setting/MemberList/hook.ts
  src/view/group/setting/MemberList/index.css.ts
  src/view/group/setting/MemberList/index.tsx
  src/view/group/setting/SettingSidebar/index.css.ts
  src/view/group/setting/SettingSidebar/index.tsx
  src/view/user/setting/MyProfile/EditForm/index.tsx
Labels: ✨ Feat, JIN, GYU, size/m

#171 [ Fix ] Modal Routing 및 사이즈 수정
  src/app/group/my-solved/page.tsx
  src/app/group/notice/page.tsx
  src/view/group/dashboard/NoticeBanner/constant.ts
  src/view/group/dashboard/NoticeBanner/index.css.ts
  src/view/group/dashboard/NoticeBanner/index.tsx
  src/view/group/dashboard/NoticeModal/NoticeDetail/index.css.ts
  src/view/group/dashboard/NoticeModal/NoticeList/index.css.ts
  src/view/group/dashboard/NoticeModal/index.css.ts
Labels: 🐛 Fix, WUZ, size/s

#161 [ Feat ] solved detail 뷰 구현
  package-lock.json
  package.json
  pnpm-lock.yaml
  public/assets/D2Coding.ttf
  src/api/solution/type.ts
  src/app/globals.css
  src/app/group/solved-detail/page.tsx
  src/common/component/Modal/index.css.tsx
  src/common/util/dom.ts
  src/shared/component/CommentBox/index.css.ts
  src/shared/type/index.ts
  src/view/group/solved-detail/CodeSection/CodeHighlighter/CodeHighlighter.tsx
  src/view/group/solved-detail/CodeSection/CodeHighlighter/code.css
  src/view/group/solved-detail/CodeSection/CodeHighlighter/prism-vsc-dark-plus.min.css
  src/view/group/solved-detail/CodeSection/CodeHighlighter/rule.ts
  src/view/group/solved-detail/CodeSection/ContextMenu/index.css.ts
  src/view/group/solved-detail/CodeSection/ContextMenu/index.tsx
  src/view/group/solved-detail/CodeSection/example.ts
  src/view/group/solved-detail/CodeSection/index.css.ts
  src/view/group/solved-detail/CodeSection/index.tsx
  src/view/group/solved-detail/CommentSection/index.css.ts
  src/view/group/solved-detail/CommentSection/index.tsx
  src/view/group/solved-detail/index.css.ts
Labels: ✨ Feat, GYU, size/l

#172 [ Feat ] 라우팅 연결 안 된 부분 연결
  src/view/user/index/GroupCard/index.tsx
Labels: ✨ Feat, JIN, size/xs
