Repository GAMZA-BAT/algohub-client, pull requests merged in 2025-08, with the labels that each got.

#438 [ Chore ] .storybook 원복
  .gitignore
  apps/client/.storybook/DocsPage.tsx
  apps/client/.storybook/WithAppRouterContext.tsx
  apps/client/.storybook/main.ts
  apps/client/.storybook/preview.ts
  apps/client/.storybook/viewport.ts
  apps/client/package-lock.json
  apps/client/src/shared/component/ExtensionAlertModal/LoginAlertModal.stories.tsx
  apps/client/src/shared/component/LoginAlertModal/LoginAlertModal.stories.tsx
  apps/client/src/shared/component/Pagination/Pagination.stories.tsx
  apps/client/src/shared/component/PromptModal/PromptModal.stories.tsx
  apps/client/tsconfig.json
  package.json
Labels: 📄 Docs, WUZ, size/xl

#437 [ Devops ] Comment CI Result
  .github/workflows/ci-pipeline.yml
  apps/client/package.json
  package.json
  pnpm-lock.yaml
  turbo.json
Labels: size/m, size/s

#434 [ Feat ] Tooltip 공통 컴포넌트 구현
  .github/CODEOWNERS.yml
  apps/client/src/common/component/Tooltip/index.css.ts
  apps/client/src/common/component/Tooltip/index.tsx
Labels: ✨ Feat, JIN, size/m

#443 [Devops] Fix deploy option
  .github/workflows/production-deploy.yml
Labels: HJO, size/xs

#440 [ Style ] 랭킹카드 네임 색상 변경
  apps/client/src/view/group/dashboard/Ranking/index.css.ts
Labels: 💄 Style, size/xs, HONG

#439 [ Fix ] z-index 및 탭 이동 수정
  apps/client/src/common/component/Modal/Modal.tsx
  apps/client/src/common/component/Modal/index.css.tsx
Labels: 🐛 Fix, GYU, size/s

#446 [ Feat ] 풀이 현황 테이블 구현
  apps/client/src/app/api/groups/index.ts
  apps/client/src/app/api/solutions/index.ts
  apps/client/src/app/api/type.ts
  apps/client/src/app/group/[groupId]/components/SolvedStatusSection/SolvedStatusTable/constant.tsx
  apps/client/src/app/group/[groupId]/components/SolvedStatusSection/SolvedStatusTable/index.css.ts
  apps/client/src/app/group/[groupId]/components/SolvedStatusSection/SolvedStatusTable/index.tsx
  apps/client/src/app/group/[groupId]/components/SolvedStatusSection/SolvedStatusTable/provider.tsx
  apps/client/src/app/group/[groupId]/components/SolvedStatusSection/index.tsx
  apps/client/src/app/group/[groupId]/notice/layout.tsx
  apps/client/src/app/group/[groupId]/page.tsx
  apps/client/src/shared/component/Table/TableElements/Body.tsx
  apps/client/src/shared/component/Table/TableElements/TableHead.tsx
  apps/client/src/shared/component/Table/TableElements/index.css.ts
  apps/client/src/shared/component/Table/index.tsx
Labels: size/m

#441 [ Refactor ] 문제 풀이 모달에서 히스토리 없을시 풀이 리스트로 리다이렉트
  apps/client/src/app/api/solutions/type.ts
  apps/client/src/app/group/[groupId]/my-solved/components/SolvedItem/SolvedItem.stories.tsx
  apps/client/src/app/group/[groupId]/solved-detail/[id]/page.tsx
Labels: ♻️ Refactor, size/s, HONG

#452 [ Feat ] 백준 아이디 required 처리
  apps/client/src/app/signup/components/AccountRegister/ProfileCreation.tsx
  apps/client/src/app/signup/components/AccountRegister/index.tsx
  apps/client/src/app/signup/components/AccountRegister/schema.ts
  apps/client/src/app/signup/components/AccountRegister/useSignupForm.ts
  apps/client/src/app/signup/components/index.css.ts
  apps/client/src/shared/hook/useCheckOnServer.ts
  apps/client/src/shared/util/form.ts
Labels: ✨ Feat, JIN, size/m

#448 [ Feat ] 피드 아이템 뷰 구현
  apps/client/src/app/[user]/components/FeedItem/index.css.ts
  apps/client/src/app/[user]/components/FeedItem/index.tsx
  apps/client/src/app/[user]/page.tsx
  apps/client/src/asset/svg/icn_enter.svg
  apps/client/src/asset/svg/icn_favorite_border.svg
  apps/client/src/asset/svg/index.ts
  apps/client/src/common/component/Avatar/Avatar.stories.tsx
  apps/client/src/common/component/Avatar/index.css.ts
  apps/client/src/common/component/Avatar/index.tsx
  apps/client/src/shared/component/CodeCard/index.css.ts
  apps/client/src/shared/component/CodeCard/index.tsx
  apps/client/src/shared/component/Like/index.css.ts
  apps/client/src/shared/component/Like/index.tsx
  apps/client/src/styles/fonts.ts
Labels: ✨ Feat, size/m, HONG
