Repository GAMZA-BAT/algohub-client, pull requests merged in 2025-06, with the labels that each got.

#404 [ Refactor ] className 교체 및 각종 컴포넌트 리팩터링
  apps/client/src/app/[user]/my-solved/page.tsx
  apps/client/src/app/[user]/not-found.tsx
  apps/client/src/app/group/[groupId]/my-solved/page.tsx
  apps/client/src/app/group/[groupId]/problem-list/page.tsx
  apps/client/src/app/not-found.tsx
  apps/client/src/common/component/Modal/index.css.ts
  apps/client/src/common/component/Spinner/index.css.ts
  apps/client/src/common/component/Spinner/index.tsx
  apps/client/src/common/hook/useTimer.ts
  apps/client/src/shared/component/FormFooter/index.css.ts
  apps/client/src/shared/component/FormFooter/index.tsx
  apps/client/src/shared/component/GroupInfoForm/index.tsx
  apps/client/src/shared/component/LoginAlertModal/index.css.ts
  apps/client/src/shared/component/LoginAlertModal/index.tsx
  apps/client/src/shared/component/SubmitButton/index.css.ts
  apps/client/src/shared/util/time.ts
  apps/client/src/styles/shared.css.ts
  apps/client/src/view/group/dashboard/NoticeModal/NoticeList/index.tsx
  apps/client/src/view/group/dashboard/NoticeModal/index.css.ts
  apps/client/src/view/group/dashboard/Ranking/index.css.ts
  apps/client/src/view/group/dashboard/Ranking/index.tsx
  apps/client/src/view/group/my-solved/SolvedItem/index.css.ts
  apps/client/src/view/group/my-solved/SolvedItem/index.tsx
  apps/client/src/view/group/problem-list/PendingList/index.css.ts
  apps/client/src/view/group/problem-list/PendingList/index.tsx
  apps/client/src/view/group/problem-list/ProblemSection/index.tsx
  apps/client/src/view/group/setting/MemberList/constant.tsx
  apps/client/src/view/group/setting/MemberList/index.css.ts
  apps/client/src/view/reset-password/ResetPassword/index.tsx
  apps/client/src/view/reset-password/SendEmailForResetPW/index.tsx
  apps/client/src/view/reset-password/SendEmailForResetPW/schema.ts
  apps/client/src/view/reset-password/index.css.ts
  apps/client/src/view/signup/AccountRegister/PasswordSetup.tsx
  apps/client/src/view/signup/AccountRegister/ProfileCreation.tsx
  apps/client/src/view/signup/AccountRegister/index.tsx
  apps/client/src/view/signup/AccountRegister/schema.ts
  apps/client/src/view/signup/EmailVerification/index.css.ts
  apps/client/src/view/signup/EmailVerification/index.tsx
  apps/client/src/view/signup/Stepper/index.css.ts
  apps/client/src/view/signup/Stepper/index.tsx
  apps/client/src/view/signup/index.css.ts
  apps/client/src/view/unsupported-browser/index.css.ts
  apps/client/src/view/unsupported-browser/index.tsx
  apps/client/src/view/user/setting/AccountManagement/AccountManagementForm/IdRegisterForm.tsx
  apps/client/src/view/user/setting/AccountManagement/AccountManagementForm/schema.ts
  apps/client/src/view/user/setting/AccountManagement/index.css.ts
  apps/client/src/view/user/setting/AccountManagement/index.tsx
Labels: ♻️ Refactor, GYU, size/l

#429 [ Fix ] 공지 모달 style 수정 및 편의성 개선
  apps/client/src/app/group/[groupId]/notice/[noticeId]/page.tsx
  apps/client/src/app/group/[groupId]/notice/create/page.tsx
  apps/client/src/app/group/[groupId]/notice/page.tsx
  apps/client/src/common/component/Modal/index.css.ts
  apps/client/src/shared/component/CommentBox/index.css.ts
  apps/client/src/shared/component/CommentBox/index.tsx
  apps/client/src/view/group/dashboard/NoticeModal/NoticeCreate/index.tsx
  apps/client/src/view/group/dashboard/NoticeModal/NoticeDetail/index.css.ts
  apps/client/src/view/group/dashboard/NoticeModal/NoticeDetail/index.tsx
  apps/client/src/view/group/dashboard/NoticeModal/NoticeList/index.css.ts
  apps/client/src/view/group/dashboard/NoticeModal/NoticeList/index.tsx
  apps/client/src/view/group/dashboard/NoticeModal/index.css.ts
Labels: 🐛 Fix, GYU, size/m, size/s

#432 [Fix] 무한루프 발생 가능성 확인
  apps/client/src/app/api/index.ts
  apps/client/src/app/provider.tsx
  apps/client/src/shared/component/RefreshTokenExpireTime/index.tsx
Labels: size/s
