Repository GAMZA-BAT/algohub-client, pull requests merged in 2025-03, with the labels that each got.

#356 fix: 잘못 사용한 react 컴포넌트 수정
  src/shared/component/Table/TableElements/Body.tsx
Labels: size/xs

#361 [ Feat ] rc cd-pipeline 연결
  .env.example
  .github/workflows/cd-pipeline.yml
  src/app/api/index.ts
Labels: ✨ Feat, JIN, size/s

#357 [ Feat ] GitHub login
  next-auth.d.ts
  src/app/[user]/layout.tsx
  src/app/[user]/page.tsx
  src/app/api/auth/actions.ts
  src/app/api/auth/callback/github/route.ts
  src/app/api/auth/type.ts
  src/app/api/index.ts
  src/app/api/notifications/index.ts
  src/app/api/type.ts
  src/app/layout.tsx
  src/app/login/page.tsx
  src/asset/svg/icn_github.svg
  src/asset/svg/index.ts
  src/asset/svg/logo_GitHub.svg
  src/auth.config.ts
  src/auth.ts
  src/common/component/Button/index.css.ts
  src/common/component/Button/index.tsx
  src/common/component/Menu/Menu.stories.tsx
  src/shared/component/Card/index.css.ts
  src/shared/component/FormFooter/GithubButton.tsx
  src/shared/component/FormFooter/action.ts
  src/shared/component/FormFooter/index.css.ts
  src/shared/component/FormFooter/index.tsx
  src/view/login/GoogleLogin/index.css.ts
  src/view/login/GoogleLogin/index.tsx
  src/view/login/LoginForm/index.tsx
  src/view/login/LoginForm/schema.ts
  src/view/login/LoginForm/useLoginForm.ts
  src/view/user/setting/SettingStep/index.tsx
Labels: ✨ Feat, WUZ, GYU, size/m

#370 [ Fix ] PUBLIC 접두어 적용
  .env.example
  .github/workflows/cd-pipeline.yml
  src/app/api/index.ts
Labels: 🐛 Fix, JIN, size/xs

#368 [ Docs ] RC, Prod 환경 env 설정
  .github/workflows/cd-pipeline.yml
  .github/workflows/rc-deploy.yml
  src/app/api/index.ts
  src/app/config.ts
Labels: 📄 Docs, WUZ, size/s

#371 [ Feat ] v1.1 회원가입 구현
  .vscode/settings.json
  src/app/api/auth/actions.ts
  src/app/api/auth/index.ts
  src/app/api/notifications/index.ts
  src/app/api/users/index.ts
  src/app/signup/page.tsx
  src/app/signup/query.ts
  src/asset/svg/icn_stepper_current.svg
  src/asset/svg/icn_stepper_done.svg
  src/asset/svg/icn_stepper_todo.svg
  src/asset/svg/index.ts
  src/auth.config.ts
  src/auth.ts
  src/route-stories/join/signup.stories.tsx
  src/shared/component/Form/index.css.ts
  src/shared/component/FormFooter/index.tsx
  src/shared/hook/useCheckOnServer.ts
  src/view/login/index.css.ts
  src/view/signup/AccountRegister/PasswordSetup.tsx
  src/view/signup/AccountRegister/ProfileCreation.tsx
  src/view/signup/AccountRegister/index.tsx
  src/view/signup/AccountRegister/schema.ts
  src/view/signup/AccountRegister/useSignupForm.ts
  src/view/signup/EmailVerification/index.tsx
  src/view/signup/EmailVerification/schema.ts
  src/view/signup/SignupForm/index.tsx
  src/view/signup/SignupForm/useSignupForm.ts
  src/view/signup/Stepper/index.css.ts
  src/view/signup/Stepper/index.tsx
  src/view/signup/constant.ts
  src/view/signup/index.css.ts
Labels: ✨ Feat, JIN, size/l

#373 [ Fix ] PRIVATE_ 접두어 재적용
  src/app/api/index.ts
Labels: size/xs

#376 [ Fix ] rc-deploy.yml 수정
  .github/workflows/rc-deploy.yml
Labels: 🐛 Fix, GYU, size/xs

#378 [ Fix ] env 설정 파일 공백 제거
  .github/workflows/rc-deploy.yml
Labels: 🐛 Fix, JIN, size/xs

#366 [ Feat ] 익스텐션 설치 안내 모달
  src/app/[user]/page.tsx
  src/app/api/index.ts
  src/app/group/[groupId]/page.tsx
  src/asset/svg/index.ts
  src/auth.ts
  src/shared/component/ExtensionAlertModal/LoginAlertModal.stories.tsx
  src/shared/component/ExtensionAlertModal/index.css.ts
  src/shared/component/ExtensionAlertModal/index.tsx
  src/shared/component/PromptModal/index.tsx
  src/shared/store/alertModal.ts
  src/shared/util/time.ts
  src/view/user/index/ExtensionAlertModal.tsx
Labels: ✨ Feat, GYU, size/m

#381 [ Feat ] rc 이미지 서버 등록
  next.config.mjs
Labels: ✨ Feat, JIN, size/xs

#383 [ Docs ] workflow set env 수정
  .github/workflows/cd-pipeline.yml
  .github/workflows/rc-deploy.yml
Labels: size/xs

#384 [ Deploy ] workflow set env 수정 (#383)
  .github/workflows/cd-pipeline.yml
  .github/workflows/rc-deploy.yml
Labels: size/xs
