Repository GAMZA-BAT/algohub-client, pull requests merged in 2025-01, with the labels that each got.

#181 [ Feat ] logout api
  src/app/[user]/not-found.tsx
  src/app/[user]/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/auth/actions.ts
  src/app/api/auth/index.ts
  src/app/layout.tsx
  src/auth.config.ts
  src/middleware.ts
  src/shared/component/Header/Profile.tsx
  src/shared/component/Header/UserMenu.tsx
  src/shared/component/QueryProvider/index.tsx
  src/view/login/LoginForm/useLoginForm.ts
Labels: ✨ Feat, GYU, size/m

#289 [ Style ] Userpage 디자인 QA 반영
  src/app/[user]/layout.tsx
  src/asset/svg/icn_my.svg
  src/styles/globalStyles.css.ts
  src/view/onboarding/Footer/index.css.ts
  src/view/onboarding/Section/index.css.ts
  src/view/user/index/GroupCard/index.css.ts
Labels: 💄 Style, JIN, size/s

#285 [ Fix ] 그룹 멤버 삭제 시 invalid hook call 오류 해결
  src/app/group/[groupId]/setting/page.tsx
  src/app/group/[groupId]/setting/query.ts
  src/view/group/setting/MemberList/MemberListProvider.tsx
  src/view/group/setting/MemberList/constant.tsx
  src/view/group/setting/MemberList/hook.ts
Labels: 🐛 Fix, JIN, size/m

#280 [ Feat ] 회원 정보 수정 및 탈퇴 / 비밀번호 변경 API 연결
  src/app/[user]/setting/action.ts
  src/app/[user]/setting/query.ts
  src/app/api/index.ts
  src/app/api/notifications/index.ts
  src/app/api/users/index.ts
  src/app/api/users/type.ts
  src/app/signup/action.ts
  src/auth.ts
  src/common/component/Avatar/index.tsx
  src/shared/component/EditAvatar/index.tsx
  src/shared/component/Header/UserMenu.tsx
  src/view/login/LoginForm/schema.ts
  src/view/login/LoginForm/useLoginForm.ts
  src/view/signup/SignupForm/useSignupForm.ts
  src/view/user/setting/AccountManagement/AccountManagementForm/index.tsx
  src/view/user/setting/AccountManagement/AccountManagementForm/schema.ts
  src/view/user/setting/AccountManagement/AccountManagementForm/useAccountForm.ts
  src/view/user/setting/AccountManagement/index.css.ts
  src/view/user/setting/AccountManagement/index.tsx
  src/view/user/setting/MyProfile/EditForm/index.tsx
  src/view/user/setting/MyProfile/EditForm/schema.ts
  src/view/user/setting/MyProfile/EditForm/useEditForm.ts
  src/view/user/setting/MyProfile/WithdrawModal/index.css.ts
  src/view/user/setting/MyProfile/WithdrawModal/index.tsx
Labels: ✨ Feat, JIN, size/l

#292 [ Fix ] 공지 모달 및 랭킹 svg 이슈
  src/app/group/[groupId]/notice/[noticeId]/page.tsx
  src/app/group/[groupId]/notice/layout.tsx
  src/app/group/[groupId]/notice/page.tsx
  src/shared/component/Pagination/index.tsx
  src/view/group/dashboard/NoticeModal/NoticeList/index.tsx
  src/view/group/dashboard/Ranking/RankingCard.tsx
  src/view/group/dashboard/Ranking/index.css.ts
Labels: 🐛 Fix, JIN, size/m

#298 [ Style ] 댓글 아이콘 정렬 수정
  src/view/group/my-solved/Header/index.css.ts
  src/view/group/my-solved/SolvedItem/index.css.ts
  src/view/group/my-solved/SolvedItem/index.tsx
Labels: 💄 Style, WUZ, size/xs

#299 [ Style ] GroupPage QA 반영
  src/app/api/groups/index.ts
  src/app/group/[groupId]/problem-list/page.tsx
  src/app/group/[groupId]/problem-list/query.ts
  src/asset/svg/icn_solved.svg
  src/asset/svg/icn_unsolved.svg
  src/asset/svg/index.ts
  src/shared/component/Pagination/index.css.ts
  src/shared/component/ProblemList/Item.tsx
  src/view/group/problem-list/ProblemSection/index.tsx
  src/view/group/problem-list/ProblemSidebar/index.tsx
  src/view/group/problem-list/index.tsx
Labels: 💄 Style, JIN, size/m

#301 [ Feat ] 풀이리스트 닉네임 필터링 적용
  src/common/component/SelectBox/index.css.ts
  src/common/hook/useDebounce.ts
  src/shared/component/SolvedFilterBar/index.tsx
  src/view/group/problem-list/SolvedList/index.tsx
Labels: ✨ Feat, WUZ, size/s

#312 [ Fix ] 알림 삭제 시 스크롤 현상 / 캐러셀 마우스 인식 못함 에러 해결
  src/common/component/Carousel/index.css.ts
  src/shared/component/Header/Notification/index.css.ts
Labels: 🐛 Fix, WUZ, size/xs

#307 [ Env ] Prepare RC Stage
  .github/workflows/rc-deploy.yml
  Dockerfile
  next.config.mjs
Labels: HJO, 🚀 Deploy

#316 [ Style ] 디자인 2차 QA 반영
  src/app/[user]/page.tsx
  src/view/group/index/MemberAvatar/index.tsx
  src/view/onboarding/Section/index.css.ts
  src/view/user/create-group/CreateGroupForm/index.css.ts
  src/view/user/create-group/CreateGroupForm/index.tsx
  src/view/user/index/ListSection/index.tsx
  src/view/user/index/index.css.ts
Labels: 💄 Style, JIN, size/s

#315 [ Fix ] 그룹 생성 데이트피커 버튼 제출 오류 / 제출 완료 시 페이지 깜빡임 해결
  src/app/[user]/create-group/page.tsx
  src/app/join-group/[code]/query.ts
  src/common/component/Calendar/index.tsx
  src/shared/component/CodeClipboard/index.tsx
  src/view/user/create-group/CreateGroupForm/index.tsx
Labels: 🐛 Fix, size/s

#303 [ Fix ] role chip layout 수정
  src/view/group/setting/MemberList/RoleList/index.css.ts
  src/view/group/setting/MemberList/constant.tsx
  src/view/group/setting/MemberList/index.css.ts
  src/view/user/setting/GroupList/GroupListTable/constant.tsx
  src/view/user/setting/GroupList/GroupListTable/index.css.ts
Labels: size/s

#323 [ Fix ] Pagination 및 공지 글쓰기 오류
  src/app/group/[groupId]/notice/create/page.tsx
  src/shared/component/Pagination/index.css.ts
  src/shared/hook/usePaginationQuery.ts
  src/view/group/dashboard/Ranking/index.tsx
Labels: 🐛 Fix, JIN, size/s

#326 [ Fix ] 그룹 참여하기 라우팅 에러 해결
  src/app/join-group/[code]/action.ts
  src/app/join-group/[code]/page.tsx
  src/app/join-group/[code]/query.ts
Labels: 🐛 Fix, WUZ, size/s

#321 [ Feat ] 풀이 필터링 키 반영 및 기능 정상화
  src/app/api/solutions/index.ts
  src/app/api/solutions/type.ts
  src/common/component/SelectBox/SelectBox.stories.tsx
  src/common/component/SelectBox/index.css.ts
  src/common/component/SelectBox/index.tsx
  src/common/component/Sidebar/index.css.ts
  src/shared/component/SolvedFilterBar/index.css.ts
  src/shared/component/SolvedFilterBar/index.tsx
  src/shared/constant/solvedFilterKey.ts
  src/view/group/solved-detail/CodeSection/CodeHighlighter/rule.ts
Labels: ✨ Feat, JIN, WUZ, size/m

#286 [ Fix ] 폼 이미지 업로드 기능 정상화
  src/app/[user]/setting/action.ts
  src/app/api/groups/schema.ts
  src/shared/component/EditAvatar/index.tsx
  src/shared/component/GroupInfoForm/index.tsx
  src/shared/component/GroupInfoForm/util.ts
  src/shared/util/form.ts
  src/view/group/setting/SettingSidebar/index.tsx
  src/view/signup/SignupForm/schema.ts
  src/view/signup/SignupForm/useSignupForm.ts
  src/view/user/create-group/CreateGroupForm/index.tsx
  src/view/user/setting/MyProfile/EditForm/schema.ts
  src/view/user/setting/MyProfile/EditForm/useEditForm.ts
Labels: 🐛 Fix, GYU, size/m

#318 [ Fix ] active 상태, 드롭다운 잘림 수정
  src/common/component/Menu/Menu.tsx
  src/shared/hook/useIntersectionObserver.ts
  src/view/group/setting/MemberList/RoleList/RoleDropdownMenu.tsx
  src/view/group/setting/MemberList/constant.tsx
  src/view/onboarding/Section/FadeInImage.tsx
  src/view/user/setting/GroupList/StatusDropdownMenu/index.css.ts
  src/view/user/setting/GroupList/StatusDropdownMenu/index.tsx
Labels: 🐛 Fix, 💄 Style, GYU, size/m

#331 [ Fix ] 문제리스트 페이지 새로고침 이슈
  src/app/group/[groupId]/problem-list/query.ts
  src/shared/component/ProblemList/ProblemEdit.tsx
  src/shared/hook/usePaginationQuery.ts
  src/view/group/problem-list/ProblemSection/index.tsx
  src/view/group/problem-list/index.tsx
Labels: size/s
