Repository GAMZA-BAT/algohub-client, pull requests merged in 2025-02, with the labels that each got.

#333 [ Fix ] 비 로그인 유저의 그룹 페이지 접근시 안내 모달 출력
  src/app/[user]/page.tsx
  src/shared/component/LoginAlertModal/index.tsx
  src/shared/component/ProtectedLink/index.tsx
  src/shared/store/alertModal.ts
  src/shared/util/form.ts
  src/view/user/index/GroupCard/LoginAlertModalController.tsx
  src/view/user/index/GroupCard/index.tsx
Labels: 🐛 Fix, GYU, size/s

#330 [ Feat ] 백준 링크 연결 및 비밀번호 설정 완료 표시
  src/app/[user]/setting/action.ts
  src/app/[user]/setting/query.ts
  src/app/api/users/index.ts
  src/shared/util/error.ts
  src/view/group/problem-list/SolvedList/ProblemInfo.tsx
Labels: ✨ Feat, JIN, size/s

#336 Fix: migrate atrifact version to v4
  .github/workflows/cd-pipeline.yml
Labels: HJO, size/xs

#338 [ Fix ] 토큰 관리 로직 변경
  package.json
  pnpm-lock.yaml
  src/app/api/auth/actions.ts
  src/app/api/auth/index.ts
  src/app/api/comments/index.ts
  src/app/api/groups/index.ts
  src/app/api/groups/ranking.ts
  src/app/api/index.ts
  src/app/api/notices/index.ts
  src/app/api/notifications/index.ts
  src/app/api/problems/index.ts
  src/app/api/solutions/index.ts
  src/app/api/users/index.ts
  src/app/signup/action.ts
  src/auth.ts
  src/shared/component/Header/Profile.tsx
  src/shared/component/Header/UserMenu.tsx
  src/shared/component/RefreshTokenExpireTime/index.tsx
  src/shared/util/form.ts
  src/shared/util/token.ts
  src/view/signup/SignupForm/useSignupForm.ts
Labels: 🐛 Fix, GYU, size/m

#340 [ Fix ] prefetch 적용
  src/app/group/[groupId]/page.tsx
  src/app/provider.tsx
  src/shared/component/QueryProvider/index.tsx
  src/shared/util/prefetch.ts
Labels: 🐛 Fix, GYU, size/m

#341 Revert "[ Fix ] prefetch 적용"
  src/app/group/[groupId]/page.tsx
  src/app/provider.tsx
  src/shared/component/QueryProvider/index.tsx
  src/shared/util/prefetch.ts
Labels: size/m

#342 Revert "[ Fix ] 토큰 관리 로직 변경"
  package.json
  pnpm-lock.yaml
  src/app/api/auth/actions.ts
  src/app/api/auth/index.ts
  src/app/api/comments/index.ts
  src/app/api/groups/index.ts
  src/app/api/groups/ranking.ts
  src/app/api/index.ts
  src/app/api/notices/index.ts
  src/app/api/notifications/index.ts
  src/app/api/problems/index.ts
  src/app/api/solutions/index.ts
  src/app/api/users/index.ts
  src/app/signup/action.ts
  src/auth.ts
  src/shared/component/Header/Profile.tsx
  src/shared/component/Header/UserMenu.tsx
  src/shared/component/RefreshTokenExpireTime/index.tsx
  src/shared/util/form.ts
  src/shared/util/token.ts
  src/view/signup/SignupForm/useSignupForm.ts
Labels: size/m

#347 [ Fix ] #308 로그인 오류 디버깅
  package.json
  pnpm-lock.yaml
  src/app/api/auth/actions.ts
  src/app/api/auth/index.ts
  src/app/api/comments/index.ts
  src/app/api/groups/index.ts
  src/app/api/groups/ranking.ts
  src/app/api/index.ts
  src/app/api/notices/index.ts
  src/app/api/notifications/index.ts
  src/app/api/problems/index.ts
  src/app/api/solutions/index.ts
  src/app/api/users/index.ts
  src/app/signup/action.ts
  src/auth.config.ts
  src/auth.ts
  src/shared/component/Header/Profile.tsx
  src/shared/component/Header/UserMenu.tsx
  src/shared/component/RefreshTokenExpireTime/index.tsx
  src/shared/util/form.ts
  src/shared/util/token.ts
  src/view/login/LoginForm/useLoginForm.ts
  src/view/signup/SignupForm/useSignupForm.ts
Labels: 🐛 Fix, GYU, size/m

#344 [ Fix ] 3차 QA 반영
  src/app/group/[groupId]/notice/page.tsx
  src/app/group/[groupId]/problem-list/action.ts
  src/app/group/[groupId]/problem-list/query.ts
  src/shared/component/GroupInfoForm/DateFormController.tsx
  src/shared/component/Header/Profile.tsx
  src/shared/util/form.ts
  src/view/group/dashboard/NoticeModal/NoticeList/index.css.ts
  src/view/group/dashboard/NoticeModal/NoticeList/index.tsx
  src/view/group/dashboard/NoticeModal/index.css.ts
  src/view/group/problem-list/RegisterForm/DateFormController.tsx
  src/view/group/problem-list/RegisterForm/PatchForm.tsx
  src/view/group/setting/SettingSidebar/index.tsx
  src/view/user/index/GroupCard/index.css.ts
  src/view/user/setting/GroupList/GroupListTable/constant.tsx
  src/view/user/setting/GroupList/GroupListTable/index.css.ts
Labels: 🐛 Fix, WUZ, size/m

#348 [ Deploy ] 0.4.9 3차 QA 반영
  .github/workflows/cd-pipeline.yml
  package.json
  pnpm-lock.yaml
  src/app/api/auth/actions.ts
  src/app/api/auth/index.ts
  src/app/api/comments/index.ts
  src/app/api/groups/index.ts
  src/app/api/groups/ranking.ts
  src/app/api/index.ts
  src/app/api/notices/index.ts
  src/app/api/notifications/index.ts
  src/app/api/problems/index.ts
  src/app/api/solutions/index.ts
  src/app/api/users/index.ts
  src/app/group/[groupId]/notice/page.tsx
  src/app/group/[groupId]/problem-list/action.ts
  src/app/group/[groupId]/problem-list/query.ts
  src/app/signup/action.ts
  src/auth.config.ts
  src/auth.ts
  src/shared/component/GroupInfoForm/DateFormController.tsx
  src/shared/component/Header/Profile.tsx
  src/shared/component/Header/UserMenu.tsx
  src/shared/component/RefreshTokenExpireTime/index.tsx
  src/shared/util/form.ts
  src/shared/util/token.ts
  src/view/group/dashboard/NoticeModal/NoticeList/index.css.ts
  src/view/group/dashboard/NoticeModal/NoticeList/index.tsx
  src/view/group/dashboard/NoticeModal/index.css.ts
  src/view/group/problem-list/RegisterForm/DateFormController.tsx
  src/view/group/problem-list/RegisterForm/PatchForm.tsx
  src/view/group/setting/SettingSidebar/index.tsx
  src/view/login/LoginForm/useLoginForm.ts
  src/view/signup/SignupForm/useSignupForm.ts
  src/view/user/index/GroupCard/index.css.ts
  src/view/user/setting/GroupList/GroupListTable/constant.tsx
  src/view/user/setting/GroupList/GroupListTable/index.css.ts
Labels: JIN, size/l, 🚀 Deploy

#350 [ Fix ] loginSchema 글자 제한 삭제
  src/view/login/LoginForm/schema.ts
Labels: 🐛 Fix, JIN, size/xs

#351 [ Fix ] prefetch 적용 re-PR
  src/app/api/auth/actions.ts
  src/app/api/auth/index.ts
  src/app/group/[groupId]/page.tsx
  src/app/provider.tsx
  src/shared/component/Header/Profile.tsx
  src/shared/component/QueryProvider/index.tsx
  src/shared/util/prefetch.ts
  src/view/login/LoginForm/useLoginForm.ts
Labels: 🐛 Fix, GYU, size/m

#353 [ Feat ] 비밀번호 재설정
  src/app/api/auth/index.ts
  src/app/api/auth/type.ts
  src/app/login/page.tsx
  src/app/reset-password/action.ts
  src/app/reset-password/page.tsx
  src/app/reset-password/query.ts
  src/asset/svg/index.ts
  src/asset/svg/logo_GitHub.svg
  src/common/component/Button/index.css.ts
  src/shared/component/AuthHeader/index.css.ts
  src/shared/component/AuthHeader/index.tsx
  src/shared/component/FormFooter/index.css.ts
  src/shared/component/SubmitButton/index.css.ts
  src/shared/constant/api.ts
  src/view/login/GoogleLogin/index.css.ts
  src/view/login/GoogleLogin/index.tsx
  src/view/login/LoginForm/index.css.ts
  src/view/login/LoginForm/index.tsx
  src/view/login/index.css.ts
  src/view/reset-password/ResetPassword/index.tsx
  src/view/reset-password/SendEmailForResetPW/index.tsx
  src/view/reset-password/index.css.ts
  src/view/user/setting/AccountManagement/AccountManagementForm/schema.ts
Labels: ✨ Feat, JIN, size/l

#354 [ Deploy ] 0.4.10 4차 QA 반영
  src/app/api/auth/actions.ts
  src/app/api/auth/index.ts
  src/app/api/auth/type.ts
  src/app/group/[groupId]/page.tsx
  src/app/login/page.tsx
  src/app/provider.tsx
  src/app/reset-password/action.ts
  src/app/reset-password/page.tsx
  src/app/reset-password/query.ts
  src/asset/svg/index.ts
  src/asset/svg/logo_GitHub.svg
  src/common/component/Button/index.css.ts
  src/shared/component/AuthHeader/index.css.ts
  src/shared/component/AuthHeader/index.tsx
  src/shared/component/FormFooter/index.css.ts
  src/shared/component/Header/Profile.tsx
  src/shared/component/QueryProvider/index.tsx
  src/shared/component/SubmitButton/index.css.ts
  src/shared/constant/api.ts
  src/shared/util/prefetch.ts
  src/view/login/GoogleLogin/index.css.ts
  src/view/login/GoogleLogin/index.tsx
  src/view/login/LoginForm/index.css.ts
  src/view/login/LoginForm/index.tsx
  src/view/login/LoginForm/schema.ts
  src/view/login/LoginForm/useLoginForm.ts
  src/view/login/index.css.ts
  src/view/reset-password/ResetPassword/index.tsx
  src/view/reset-password/SendEmailForResetPW/index.tsx
  src/view/reset-password/index.css.ts
  src/view/user/setting/AccountManagement/AccountManagementForm/schema.ts
Labels: JIN, size/l, 🚀 Deploy
