Repository GAMZA-BAT/algohub-client, pull requests merged in 2025-05, with the labels that each got.

#403 [ Feat ] 깃헙 계정의 회원탈퇴 정상화
  src/auth.ts
  src/view/login/LoginForm/schema.ts
  src/view/user/setting/MyProfile/WithdrawModal/index.css.ts
  src/view/user/setting/MyProfile/WithdrawModal/index.tsx
Labels: ✨ Feat, GYU, size/s

#407 [ Style ] Notice 모달 뷰 UI 수정
  package.json
  src/view/group/dashboard/NoticeModal/NoticeDetail/index.css.ts
  src/view/group/dashboard/NoticeModal/NoticeDetail/index.tsx
  src/view/group/dashboard/NoticeModal/index.css.ts
Labels: size/m

#408 [ Style ] 데이트피커 UI 개선
  src/common/component/Calendar/index.css.ts
  src/common/component/Calendar/index.tsx
Labels: size/s

#405 [ Feat ] 이벤트 코드젠, 믹스패널 도입
  biome.json
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/[user]/layout.tsx
  src/app/api/index.ts
  src/app/provider.tsx
  src/auth.ts
  src/common/component/PVTracker/index.tsx
  src/sdk/__generated__/custom.gen.ts
  src/sdk/__generated__/pv.gen.ts
  src/sdk/codegen/generateEvent.ts
  src/sdk/event/custom.event.mjs
  src/sdk/event/pv.event.mjs
  src/sdk/mixpanel.ts
  src/sdk/webpackGenerateEventPlugin.cjs
  src/shared/constant/config.ts
  src/shared/constant/url.ts
  src/shared/hook/usePvEvent.ts
  src/shared/hook/useTrack.ts
  src/view/login/LoginForm/useLoginForm.ts
  src/view/user/setting/MyProfile/index.tsx
  tsconfig.json
Labels: size/m

#414 [ Fix ] 빌드 프로세스 종료되는 이슈
  src/sdk/webpackGenerateEventPlugin.cjs
Labels: 🐛 Fix, JIN, size/xs

#412 [ Fix ] 그룹 초대 재수락 시 에러 핸들링
  src/app/group/[groupId]/withdraw/action.ts
  src/app/group/[groupId]/withdraw/page.tsx
  src/app/join-group/[code]/action.ts
  src/app/join-group/[code]/page.tsx
Labels: 🐛 Fix, size/s

#410 [ Fix ] 알람 설정 아이콘 수정
  src/view/user/setting/SettingStep/index.tsx
Labels: 🐛 Fix

#409 [ Feat ] 프로필 이미지 UI 변경
  src/common/util/string.ts
  src/shared/component/EditAvatar/index.css.ts
  src/shared/component/EditAvatar/index.tsx
  src/shared/util/form.ts
  src/view/user/setting/MyProfile/EditForm/index.tsx
Labels: ✨ Feat, size/m

#416 [ Deploy ] v.1.0.1 빌드 프로세스 종료 이슈
  src/app/group/[groupId]/withdraw/action.ts
  src/app/group/[groupId]/withdraw/page.tsx
  src/app/join-group/[code]/action.ts
  src/app/join-group/[code]/page.tsx
  src/common/util/string.ts
  src/sdk/webpackGenerateEventPlugin.cjs
  src/shared/component/EditAvatar/index.css.ts
  src/shared/component/EditAvatar/index.tsx
  src/shared/util/form.ts
  src/view/user/setting/MyProfile/EditForm/index.tsx
  src/view/user/setting/SettingStep/index.tsx
Labels: size/m, 🚀 Deploy

#417 [ Fix ] 유저정보 수정 api 에러 메세지 표시
  src/app/[user]/setting/action.ts
  src/app/[user]/setting/query.ts
  src/app/api/auth/actions.ts
  src/app/api/index.ts
  src/app/api/notifications/index.ts
  src/app/api/type.ts
  src/app/api/users/index.ts
  src/app/query.ts
  src/auth.ts
  src/shared/component/Header/Profile.tsx
  src/shared/constant/api.ts
  src/shared/util/form.ts
  src/view/login/LoginForm/useLoginForm.ts
  src/view/user/setting/MyProfile/EditForm/index.tsx
  src/view/user/setting/MyProfile/EditForm/useEditForm.ts
Labels: 🐛 Fix, size/m

#420 [ Deploy ] v.1.0.1 버그 수정
  src/app/[user]/setting/action.ts
  src/app/[user]/setting/query.ts
  src/app/api/auth/actions.ts
  src/app/api/auth/index.ts
  src/app/api/index.ts
  src/app/api/notifications/index.ts
  src/app/api/type.ts
  src/app/api/users/index.ts
  src/app/query.ts
  src/auth.ts
  src/shared/component/Header/Profile.tsx
  src/shared/constant/api.ts
  src/shared/util/form.ts
  src/view/group/dashboard/NoticeModal/NoticeList/index.tsx
  src/view/login/LoginForm/useLoginForm.ts
  src/view/user/setting/AccountManagement/AccountManagementForm/IdRegisterForm.tsx
  src/view/user/setting/MyProfile/EditForm/index.tsx
  src/view/user/setting/MyProfile/EditForm/useEditForm.ts
Labels: size/m, 🚀 Deploy

#427 [ Docs ] Pnpm 버전 corepack으로 명시
  .github/actions/pnpm-cache/action.yml
  .github/workflows/ci-pipeline.yml
  .gitignore
  package.json
Labels: size/s

#428 [ Docs ] add cache action to cd pipeline
  .github/workflows/cd-pipeline.yml
Labels: size/s

#421 [ Feat ] 비밀번호 일치 캡션
  src/shared/util/form.ts
  src/view/signup/AccountRegister/PasswordSetup.tsx
  src/view/signup/AccountRegister/ProfileCreation.tsx
  src/view/signup/AccountRegister/index.tsx
  src/view/signup/AccountRegister/schema.ts
  src/view/signup/AccountRegister/useSignupForm.ts
  src/view/signup/SignupForm/index.css.ts
Labels: ✨ Feat, GYU, size/m

#431 [ Docs ] rc-deploy에 docker username, password 다시 추가
  .github/workflows/rc.deploy.workflow.yml
Labels: size/xs, rc-deploy
