Repository GAMZA-BAT/algohub-client, pull requests merged in 2025-04, with the labels that each got.

#386 [ Fix ] 5차 QA 수정
  src/app/api/auth/actions.ts
  src/app/api/auth/callback/github/route.ts
  src/app/api/index.ts
  src/app/group/[groupId]/notice/query.ts
  src/auth.ts
  src/common/component/Calendar/index.tsx
  src/shared/component/Form/index.css.ts
  src/shared/component/Form/index.tsx
  src/shared/constant/api.ts
  src/shared/util/error.ts
  src/shared/util/time.ts
  src/view/group/setting/SettingSidebar/index.tsx
  src/view/signup/EmailVerification/index.tsx
  src/view/user/index/ExtensionAlertModal.tsx
  src/view/user/setting/MyProfile/EditForm/schema.ts
  src/view/user/setting/MyProfile/EditForm/useEditForm.ts
Labels: ✨ Feat, 🐛 Fix, GYU, size/m

#391 [ Fix ] rc일 때 그룹 초대 링크 분기 처리
  .github/PULL_REQUEST_TEMPLATE.md
  src/auth.ts
  src/shared/constant/url.ts
  src/shared/hook/useClipboard.ts
Labels: size/s

#393 [ Fix ] 5차 디자인 QA 반영
  src/app/[user]/setting/query.ts
  src/app/api/notifications/index.ts
  src/app/api/users/index.ts
  src/app/api/users/type.ts
  src/app/reset-password/action.ts
  src/app/reset-password/query.ts
  src/app/signup/query.ts
  src/shared/component/ExtensionAlertModal/index.tsx
  src/shared/component/PromptModal/index.css.ts
  src/view/login/LoginForm/index.tsx
  src/view/reset-password/SendEmailForResetPW/index.css.ts
  src/view/reset-password/SendEmailForResetPW/index.tsx
  src/view/signup/AccountRegister/schema.ts
  src/view/signup/EmailVerification/index.css.ts
  src/view/signup/EmailVerification/index.tsx
  src/view/signup/index.css.ts
  src/view/user/setting/MyProfile/EditForm/index.css.ts
  src/view/user/setting/MyProfile/index.css.ts
Labels: size/m

#394 [ Fix ] 문제 번호 제거
  src/view/group/problem-list/SolvedList/index.tsx
Labels: 🐛 Fix, JIN, size/xs

#398 [ Fix ] SolutionList 데이터 캐싱 문제
  src/app/api/users/index.ts
  src/app/api/users/type.ts
  src/app/group/[groupId]/problem-list/[id]/query.ts
  src/view/group/problem-list/SolvedList/index.tsx
Labels: 🐛 Fix, JIN, size/s

#395 [ Fix ] DatePicker 값 정상화
  src/common/component/Calendar/index.tsx
Labels: 🐛 Fix, GYU, size/xs

#399 [ Deploy ] v0.5.2 5차 QA 반영(2)
  .github/PULL_REQUEST_TEMPLATE.md
  src/app/[user]/setting/query.ts
  src/app/api/notifications/index.ts
  src/app/api/users/index.ts
  src/app/api/users/type.ts
  src/app/group/[groupId]/problem-list/[id]/query.ts
  src/app/reset-password/action.ts
  src/app/reset-password/query.ts
  src/app/signup/query.ts
  src/auth.ts
  src/common/component/Calendar/index.tsx
  src/shared/component/ExtensionAlertModal/index.tsx
  src/shared/component/PromptModal/index.css.ts
  src/shared/constant/url.ts
  src/shared/hook/useClipboard.ts
  src/view/group/problem-list/SolvedList/index.tsx
  src/view/login/LoginForm/index.tsx
  src/view/reset-password/SendEmailForResetPW/index.css.ts
  src/view/reset-password/SendEmailForResetPW/index.tsx
  src/view/signup/AccountRegister/schema.ts
  src/view/signup/EmailVerification/index.css.ts
  src/view/signup/EmailVerification/index.tsx
  src/view/signup/index.css.ts
  src/view/user/setting/MyProfile/EditForm/index.css.ts
  src/view/user/setting/MyProfile/index.css.ts
Labels: JIN, size/m, 🚀 Deploy

#397 [ Fix ] 문제 추가 시 탭 자동 변경 및 mutation 코드 수정
  src/app/[user]/setting/query.ts
  src/app/api/index.ts
  src/app/group/[groupId]/notice/query.ts
  src/app/group/[groupId]/problem-list/page.tsx
  src/app/group/[groupId]/problem-list/query.ts
  src/app/group/[groupId]/setting/query.ts
  src/app/group/[groupId]/solved-detail/[id]/query.ts
  src/app/query.ts
  src/common/component/Carousel/index.css.ts
  src/shared/component/Header/Notification/index.tsx
  src/shared/component/WithdrawDialog/query.ts
  src/view/group/dashboard/NoticeModal/NoticeDetail/query.ts
Labels: ✨ Feat, 🐛 Fix, GYU, size/m

#401 [ Fix ] 문제 마우스 이벤트 정상화
  src/shared/component/CommentBox/index.tsx
  src/shared/component/Header/Notification/NotificationItem.tsx
  src/shared/component/ProblemList/Item.tsx
  src/shared/hook/useA11yHandler.ts
  src/view/group/dashboard/NoticeModal/NoticeDetail/index.tsx
  src/view/group/my-solved/SolvedItem/index.css.ts
  src/view/group/my-solved/SolvedItem/index.tsx
  src/view/group/problem-list/PendingList/Item.tsx
  src/view/group/problem-list/SolvedList/ProblemInfo.tsx
Labels: 🐛 Fix, GYU, size/m

#402 [ Feat ] OAuth 계정 여부 추가
  next-auth.d.ts
  src/app/[user]/setting/query.ts
  src/app/api/users/index.ts
  src/app/api/users/type.ts
  src/auth.ts
  src/view/login/LoginForm/index.tsx
  src/view/user/setting/AccountManagement/AccountManagementForm/index.tsx
  src/view/user/setting/MyProfile/EditForm/index.tsx
  src/view/user/setting/MyProfile/EditForm/useEditForm.ts
  src/view/user/setting/MyProfile/WithdrawModal/index.tsx
Labels: ✨ Feat, GYU, size/m
